### PR TITLE
ADDED THE PICTURES

### PR DESCRIPTION
**Pull request by HS202022**
## Issues Identification

Closes: #680 

## Description
added the pictures
### Summary
ADDED THE PICTURES

### Details
ADDED THE PICTURES

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@HS202022 while i was checking the preview,

still i can't see the pictures 

image

can you check it and update it.

**Comment by HS202022** [comment]
> @HS202022 while i was checking the preview,
> 
> still i can't see the pictures
> 
> image
> 
> can you check it and update it.

yeah i will need some time

**Comment by vivekvardhan2810** [comment]
Okay, No problem, take your time @HS202022 and update it.

**Comment by HS202022** [comment]
the files are not getting uploaded i will delete the respo and again do it

**Comment by vivekvardhan2810** [comment]
@HS202022 no need to do this now, i will look for this later, till then you can look for other features.

**Comment by HS202022** [comment]
ok fine thank you

**Pull request closed without merging**
