### PR TITLE
Formatted "About ML fusion" differently

### PR DESCRIPTION
**Pull request by harbakshsinghbaath**
I have changed the size, spacing, colour of fonts etc to those which I think go well along with the website and have a better look to it and look more organized.... if you have any other changes or suggestions in the changes I made please tell

### CODE REVIEW

**Comment by harbakshsinghbaath** [comment]
since @Nandini-13 has added the picture i can add it to my updated version too. 
And the error is caused by the use of <br> but I feel the spacing looks like a welcome change

**Comment by vivekvardhan2810** [comment]
@harbakshsinghbaath pls resolve the conflicts.

**Comment by vivekvardhan2810** [comment]
@harbakshsinghbaath and pls resolve the conflicts.

**Comment by vivekvardhan2810** [comment]
@harbakshsinghbaath pls mention the issue number, as it will be helpful for me to merge

**Comment by harbakshsinghbaath** [comment]
yes its issue #17

**Comment by vivekvardhan2810** [comment]
@harbakshsinghbaath I will check and merge it tomorrow.

**Comment by harbakshsinghbaath** [comment]
sorry its actually issue #17 and i have edited the picture to now have rounded corners along with a shadow for the little details
image

**Comment by vivekvardhan2810** [comment]
@harbakshsinghbaath I will check and merge it tomorrow

**Pull request merged**
