### PR TITLE
Navbar Oversizing on Mobile – Requires Responsive Adjustment #1068

### PR DESCRIPTION
**Pull request by Ankul8471**
issue no. #1068

Screenshot 2024-10-27 232015
Screenshot 2024-10-27 232032

### CODE REVIEW

**Comment by Ankul8471** [comment]
please merge it and if possible then please assign me at least level 2 It helps me a lot. thank you....

**Comment by vivekvardhan2810** [comment]
@Ankul8471 as i can see only 1 file change.

if i assign you level 2 then there will be some issues from my side. as a project admin and program manager reviews all this PR's and it's a clear instruction.

so please understand.

As this PR's and issues are reviewed by program manager.

so that's why

**Comment by Ankul8471** [comment]
ok sir No problem its only request

**Comment by Ankul8471** [comment]
thank you sir....

**Comment by vivekvardhan2810** [comment]
@Ankul8471 thank you for contributing to ML Fusion Labs.

your contribution gives value to our repository.

Now please do work on other projects.

**Pull request merged**
