### PR TITLE
: Responsive Design and Content Overflow Issue #133 

### PR DESCRIPTION
**Pull request by sahhoArjun097**
added Responsive Design and  solve Content Overflow Issue and make feature section responsive .

https://github.com/user-attachments/assets/904c2234-62e0-446a-92eb-df504031037d

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

### CODE REVIEW

**Comment by sahhoArjun097** [comment]
issue number is #133

**Comment by Tejashri-Taral** [comment]
@sanjay-kv and @MastanSayyad can you review this?

**Comment by vivekvardhan2810** [comment]
@Tejashri-Taral i have reduced the level.

**Comment by vivekvardhan2810** [comment]
@MastanSayyad sorry from my side.

**Pull request merged**
