### PR TITLE
Updated courseDetails.js

### LINKED ISSUE #1043: Ensure Consistent Data Structure and Add Validation for Course Details
The `courseDetails.js` file contains details about various courses, which are structured as objects in an array. While the data is well-organized, adding consistency checks and validation will help prevent missing or incorrectly formatted properties, which may cause runtime errors or inconsistent UI behavior. This issue proposes adding validation to enforce a consistent data structure.

**Proposed Solution:**

1. **Consistent Data Structure:** Define a standard structure for each course object, including required properties such as `id`, `title`, `price`, `instructors`, `learningOutcomes`, and `requirements`. All courses should follow this structure to maintain data integrity.

2. **Data Validation:** Implement a validation step to check for the presence and type of required properties in each course object.

3. **Dynamic Discount Calculation (Optional):** If the project’s UI displays a discount percentage, calculate it dynamically from `strikedPrice` and `price` rather than storing a hard-coded value. This will ensure accurate discounts across the UI.

**_Kindly add gssoc-ext with level and hacktoberfest-accepted labels!_** @vivekvardhan2810

### PR DESCRIPTION
**Pull request by smog-root**
Closes #1043 

Can you please upgrade the level?? @vivekvardhan2810 

kindly add all the labels!

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@smog-root can you please share the screenshots of the outputs like the changes that you have done.

**Comment by vivekvardhan2810** [comment]
And @smog-root one more thing.

as i can see only 1 file change.

if i assign you level 2 then there will be some issues from my side. as a project admin and program manager reviews all this PR's and it's a clear instruction.

so please understand.

As this PR's and issues are reviewed by program manager.

so that's why

will it be okay for you if i give this in level 1.

**Comment by smog-root** [comment]
It's fine!! With level1 al that matters is contribution!

I'm in college. I can't work now!!

I will send the screenshots at 4pm!!

Please understand!! @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Okay @smog-root.

**Comment by smog-root** [comment]
**Validation of Course Data:**

- The `validateCourseData` function checks if required properties are present and defined.
- It also verifies that `instructors`, `learningOutcomes`, and `requirements` are arrays.

**Discount Calculation:**

- The `calculateDiscount` function computes the discount percentage based on the `striked` price and current price.

**Updating Course Details:**

- You loop through `courseDetails` to add a `discountPercentage` property to each course based on the calculated discount.

<br>
Screenshot_26-10-2024_111934_github com

**Comment by vivekvardhan2810** [comment]
@smog-root i am asking the screenshots from the website.

Not the screenshot of the code.

i want the screenshots from the website. (like the changes)

Before Screenshot: (how it was in website)

After Screenshot : (now how it is in website after the changes).

**Comment by smog-root** [comment]
Nothing is changed on the front end.. I just changed the back end!!

Please understand!! @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@smog-root as your saying you have changed the backend.

so what feature did you add it and how these changes implement in backend. I didn't understand.

Please explain this, so that i can review and merge this PR.

**Comment by smog-root** [comment]
The `validateCourseData` function checks if required properties are present and defined.
And It also verifies that `instructors`, `learningOutcomes`, and `requirements` are arrays.

**Comment by vivekvardhan2810** [comment]
Okay @smog-root.

Done.

Thank you for contributing to ML Fusion Labs.

please do contribute to other projects.

**Review by vivekvardhan2810 — APPROVED** [review]

**Pull request merged**
