### PR TITLE
For issue #591, privacy.html has been updated.

### PR DESCRIPTION
**Pull request by anadisharma121**
## Issues Identification

Closes: #591 

### Summary
Major changes in privacy policy page to make it look more genuine and professional.

### Details
Written all the regarding terms of policy like collecting user info, security of user info, sharing of user info, etc. 

## Types of Changes

- [x] New feature (non-breaking change that adds functionality)
- [x] Other (Updated the privacy policy with proper terms):

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## This is how the page looks like now
image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@anadisharma121 from my side i can't merge it.

can you please update this and it is showing failed.

**Comment by anadisharma121** [comment]
@vivekvardhan2810 I'm not able to understand why it's getting failed. Please help me with this.

**Comment by vivekvardhan2810** [comment]
@anadisharma121 can you do one thing, you can close this PR, and then create new PR.

Will it be okay for you.

**Comment by anadisharma121** [comment]
@vivekvardhan2810 All my changes are working fine in the [deploy preview](https://deploy-preview-599--ml-fusion-lab.netlify.app/) . Please merge the pull request.

**Comment by anadisharma121** [comment]
> @anadisharma121 can you do one thing, you can close this PR, and then create new PR.
> 
> Will it be okay for you.
> 
> I think by this way it may get solved.
okk

**Pull request closed without merging**
