### PR TITLE
Enhance Cousrses

### PR DESCRIPTION
**Pull request by shreya20v**
## Issues Identification [Mention The Feature]: Enhance Courses #556 
Closes: #556

## Description
I have added the descriptions of all 6 courses on the website. 

### Summary
The descriptions include a summary of each course and the main topics it will cover. The addition has been made with some effects so that it goes with the aesthetic of the page.  For eg: 
Description:
Data science is a multidisciplinary field that utilizes various techniques, processes, algorithms, and systems to extract insights and knowledge from structured and unstructured data. Some essentials fundamental to the practice of data science that the course will cover are:

- Mathematics and Statistics
- Programming Skills
- Data Manipulation and Cleaning
- Data Visualization
- Machine Learning

### Details
The description has been added in a flip style to make it more attractive and appealing to the user. Due to the size of the content I had to make a minor change to the size of the card.  
I have edited a HTML and a CSS file for the Courses page. 
In the CSS file description (for underlying, pointer, and formatting) styling and flip-card styling (for the flip-card effect) have been added.
In the HTML file courses category has been edited.

_Please check the boxes that apply_
- [ ] Bugfix (non-breaking change that fixes an issue)
- New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

-  My code follows the style guidelines of this project
- I have performed a self-review of my own code
-  I have commented my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
- My changes generate no new warnings
- My changes do not break the current system and pass all existing test cases
-  I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes

## Screenshots
Before Changes: 
image

After Changes:
image image
image
image
image
image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@shreya20v while i was checking the preview, it is looking like this 

it is too big

image

and the border margin is also too long.

image

and can you add the description.

image

in these small cards.

image

And can you close this PR, as i have updated the website just now .

so that you can sync the repository and work on it.

Will it be okay for you.

**Comment by vivekvardhan2810** [comment]
@shreya20v it will be okay from my side.

**Comment by shreya20v** [comment]
@okay. I'll do it.

**Comment by vivekvardhan2810** [comment]
@shreya20v And can you close this PR, As i have updated the website.

So that you can sync the repository and update it, and then you can create a new PR.

Will it be okay for you.

If it is okay for you.

**Pull request closed without merging**
