### PR TITLE
Added login and Signin Pages #65

### LINKED ISSUE #65: Create a new and interactive Login and Signin pages
I would like to create a login in page and signin page to this project. A website like this must have this two page so that the registered people can have access to courses and project.

I propoes a clean and user friendly pages which also matches with the main page theme and design.

Would u assign me this task under gssoc-ext tag.

### PR DESCRIPTION
**Pull request by yeshwanth-ds**
Screenshot 2024-10-03 180350
Screenshot 2024-10-03 180356
Screenshot 2024-10-03 180404

Closes #65

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@yeshwanth-ds pls resolve the conflicts.

**Comment by yeshwanth-ds** [comment]
@vivekvardhan2810 i hope the conflict has been resloved Plese let me know if there is any other problem

**Comment by vivekvardhan2810** [comment]
Okay @yeshwanth-ds will let you know after checking it.

**Comment by vivekvardhan2810** [comment]
@yeshwanth-ds pls resolve the conflict.

**Comment by vivekvardhan2810** [comment]
@yeshwanth-ds pls resolve the conflicts.

**Pull request closed without merging**
