### PR TITLE
#604 - Organized Whole Code

### PR DESCRIPTION
**Pull request by PrAyAg9**
## Issues Identification

Closes: #604

## Description

*** Please CHECK THERE MAY BE SOME INCONSISTENCIES but i have done a lot of lot of work ..............  ## IT TOOK FOREVER ----as even header and foooter html was not organized in some files ---- still i say 95% of work is done you can check it ....

Creating a whole new website is easy than reviewing code by many others. Now i understand this. 
I hope you understand the work behind this and approve this....

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ yes ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [yes ] My code follows the style guidelines of this project
- [yes] I have performed a self-review of my own code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [yes ] I have made corresponding changes to the documentation
- [ yes] My changes generate no new warnings
- [ yes] My changes do not break the current system and pass all existing test cases
- [ yes] I have added tests that prove my fix is effective or that my feature works
- [ yes] New and existing unit tests pass locally with my changes

## Screenshots

image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@PrAyAg9 Done, Good. and Thank you for making this in very good format.

**Comment by PrAyAg9** [comment]
hey you forgot to add level label

**Comment by vivekvardhan2810** [comment]
yes, i will add it, my badd.

**Comment by vivekvardhan2810** [comment]
@PrAyAg9 can you check it, i have added it.

**Comment by PrAyAg9** [comment]
level bro it took more time than writing backend of my melodify app earlier

**Comment by PrAyAg9** [comment]
Thanks a lot

**Comment by vivekvardhan2810** [comment]
Again Sorry from my side.@PrAyAg9 I have updated.

**Pull request merged**
