### PR TITLE
Add SMS Spam Classification Tutorial Using LSTM

### LINKED ISSUE #941: [Mention The Feature]: Adding Tutorial on how to develop a Email Spam Classifier Using DL in project page website.
### Is your feature request related to a problem? Please describe.

We need to create a comprehensive tutorial that guides users through the process of developing an email spam classifier using deep learning techniques. This tutorial should be suitable for beginners and cover all essential aspects, from data preparation to model evaluation.

### Describe the solution you'd like.

**Proposed Steps:**

1. **Introduction:**
   - Brief overview of spam classification and its importance.
   - Explanation of deep learning and its advantages in classification tasks.

2. **Dataset:**
   - Identify and provide access to a suitable dataset for email classification (e.g., Enron Email Dataset, SpamAssassin Public Corpus).
   - Instructions on how to preprocess the dataset (cleaning text, removing stop words, etc.).

3. **Model Development:**
   - Step-by-step guide on setting up the deep learning environment (e.g., using TensorFlow/Keras or PyTorch).
   - Building the model architecture (e.g., using LSTM, CNN, or Transformer-based models).
   - Explanation of hyperparameters and their importance.

4. **Training the Model:**
   - Instructions on training the model, including batching, validation, and metrics.
   - Techniques for optimizing model performance (e.g., early stopping, learning rate scheduling).

5. **Evaluation:**
   - Methods to evaluate the model's performance using metrics like accuracy, precision, recall, and F1 score.
   - Visualizations of the results (e.g., confusion matrix, ROC curve).

6. **Deployment:**
   - Brief overview of how to deploy the trained model for real-time email classification (e.g., using Flask or FastAPI).

7. **Conclusion:**
   - Summary of key takeaways and potential improvements for the classifier.
   - Suggestions for further reading or projects related to spam classification.

### Describe alternatives you've considered.

_No response_

### Additional context.

_No response_

### Show us the magic with screenshots

_No response_

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by IkkiOcean**
**Description**:
This pull request introduces a comprehensive tutorial on building an SMS spam classification model using a Recurrent Neural Network (RNN) with Keras. The tutorial guides users through the entire process, from data preprocessing to model evaluation, ensuring that readers can follow along and replicate the results.

**Key Features**:
- **Data Loading and Preprocessing**: Instructions on loading the SMS spam dataset and preprocessing the text data by cleaning, tokenizing, and removing stopwords.
- **Model Architecture**: Detailed steps to define the RNN model architecture using Keras, including embedding layers, LSTM units, and dense layers.
- **Training the Model**: Implementation of model training with early stopping to prevent overfitting, including options for batch size and epochs.
- **Model Evaluation**: Instructions on evaluating the model’s performance on a test set, with results indicating a loss of **0.08** and an accuracy of **98%**.

**Usage**:
Users can follow the tutorial step-by-step to build their own SMS spam classification models, gaining insights into deep learning techniques and Keras functionalities.

**Conclusion**:
This tutorial serves as a valuable resource for beginners and experienced practitioners alike, providing a hands-on approach to implementing deep learning models for text classification tasks. 

**Changes Made**:
- Added the complete tutorial content in markdown format, including code snippets and explanations.
- Ensured the tutorial is well-structured and easy to follow, with clear sections for each step of the process.

### related issue:
- Closes #941

### CODE REVIEW

**Comment by IkkiOcean** [comment]
this is nice. while making tutorial I myself noticed new things :)

**Comment by vivekvardhan2810** [comment]
> this is nice. while making tutorial I myself noticed new things :)

@ikkiOcean, what are the new things you have seen, noticed and explored.

**Review by vivekvardhan2810 — APPROVED** [review]
Done.

**Comment by IkkiOcean** [comment]
> > this is nice. while making tutorial I myself noticed new things :)
> 
> @IkkiOcean, what are the new things you have seen, noticed and explored.
> 
> please tell us, so that i can also know about these.

well for starter. I didnt knew RNN can be used for image classification also. it work very well with CNN to extract text. this I learnt while looking for resources to explain my model better.

**Comment by vivekvardhan2810** [comment]
yes @IkkiOcean.

**Pull request merged**
