### PR TITLE
Text readability and text overlapping figured out.

### PR DESCRIPTION
**Pull request by akansha-02**
#48 closes

Screenshot 2024-10-04 010013
Earlier the text of headings (such as Structured Learnings etc.) and its description  were coming out of the box with are now aligned properly with the help of some properties and are now more readable. 

Screenshot 2024-10-04 011925
The text above the cover images now seems more appealing.
The texts Headings (like About ML Fusion Lab) can be now distinguished well from its descriptions.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@akansha-02 pls resolve the conflicts

**Comment by akansha-02** [comment]
Conflict resolved. Please check and merge.

**Comment by vivekvardhan2810** [comment]
@akansha-02 pls resolve the conflicts.

**Comment by akansha-02** [comment]
Conflict resolved. Please check and merge.

**Pull request merged**
