### PR TITLE
fixes: Course Cards Layout Problem on /courses Route #478

### PR DESCRIPTION
**Pull request by sagarbendale2004**
## Issues Identification

Closes: #478 

## Description
The course cards on the /courses route were previously stuck to the left and right edges of the page, with no margin on the X-axis. This created a cramped and unbalanced layout, affecting the overall user experience.

## Changes Made:

- Added appropriate margins to the left and right sides of the course cards container to ensure proper spacing from the page edges.
- Reduced the gap between the course cards slightly to maintain a balanced and clean layout.

## Steps to Verify:

- Navigate to the /courses route.
- Confirm that the first and last course cards no longer stick to the edges of the page.
- Verify that there is now consistent margin on both the left and right sides, creating a more balanced layout.

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots
Screenshot 2024-10-12 131815

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 while i was checking the preview

it's coming like this

image

i can't see both the images

please check and make the required changes.

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 please check the above message and update it.

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 please resolve the conflicts.

image

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 it is coming like this.

image

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 now it has gone entirely

image

There is a way to solve this,

Will it be okay If i close this PR, so that you can sync the repository and make updates, and then Create NEW Pull Request.

**Comment by sagarbendale2004** [comment]
@vivekvardhan2810 check the latest preview of my changes it solved this issue very well so you can merge the pull request after reviewing the preview. if any update then please tell me.

**Comment by vivekvardhan2810** [comment]
Done. @sagarbendale2004 Good.

**Pull request merged**
