### PR TITLE
Updated the terms and conditions page 

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #975 
Screenshot 2024-10-23 at 11 44 28 PM

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]
LGTM

**Comment by shubhagarwal1** [comment]
Hey @vivekvardhan2810 you there?

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 Yes.

**Comment by vivekvardhan2810** [comment]
please tell me @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> yes, please tell me @shubhagarwal1

can i fix the email us page

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 yes you can do this, but this will be the last issue from my side that i am gonna assign you

As i have said early that i will be inactive from 25th.

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 and also there isn't email page created yet.

**Pull request merged**
