### PR TITLE
enhance card design

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #793

image
Before merging this PR

Screenshot 2024-10-20 115738
After merging this PR

_Please check the boxes that apply_
- [ ✅] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [✅ ] My code follows the style guidelines of this project
- [ ✅] I have performed a self-review of my own code
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [ ✅] My changes generate no new warnings
- [ ✅] My changes do not break the current system and pass all existing test cases
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [ ✅] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah please resolve the conflicts.

**Comment by Sawan-Kushwah** [comment]
@vivekvardhan2810 done!

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah while i was checking the deploy preview.

why did you change the testimonial section.

it's coming like this.

image

please make the required changes.

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah have you done.

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah for now i am merging this, make sure to don't repeat this next time.

**Comment by Sawan-Kushwah** [comment]
@vivekvardhan2810 I think by mistake it get removed I will not repeat it again

**Pull request merged**
