### PR TITLE
#568 solved(Updated feedback form page)

### PR DESCRIPTION
**Pull request by eshaalal**
before :

Screenshot 2024-10-14 151639

after:

Screenshot 2024-10-14 151256
  

I have added the navbar, footer and updated the UI

### CODE REVIEW

**Comment by eshaalal** [comment]
@ML-Fusion-Lab I have solved #568 please have a look

**Comment by vivekvardhan2810** [comment]
@eshaalal can you make the feedback page better.

image

And add the star ratings.

image

And add the favicon logo 

image

**Comment by eshaalal** [comment]
Sure!

**Comment by vivekvardhan2810** [comment]
Done. @eshaalal, Good Work.

**Pull request merged**
