### PR TITLE
#852 I would like to implement the mobile responsive design for Proje…

### PR DESCRIPTION
**Pull request by ambarmishraa**
…ct Page

## Issues Identification

Closes: #852 

### Summary
This pull request addresses the issue of the Feature Project Section not being responsive. It implements a mobile-responsive design to ensure that the section adapts seamlessly to different screen sizes, including mobile, tablet, and desktop. The changes are necessary to improve user experience, making the section more accessible, readable, and navigable on smaller screens, which will lead to better engagement and usability for all users.

### Details
This pull request includes the following changes to make the Feature Project Section responsive:

Layout Enhancements:

Utilized CSS Flexbox/Grid to create a flexible layout that adapts to various screen sizes.
Implemented a multi-column layout for larger screens, which transitions to a single-column layout on smaller devices for improved readability.
Responsive Typography:

Applied media queries to adjust font sizes and spacing dynamically based on the screen width, ensuring that text remains legible and well-proportioned across devices.
Image Responsiveness:

Made all project images responsive by setting max-width: 100% and adjusting their height to maintain aspect ratios.
Introduced srcset attributes for images to serve appropriate sizes based on device resolution, enhancing performance and loading times.
Interactive Elements:

Ensured that buttons and links are adequately sized and spaced for touch interactions on mobile devices, improving usability.
Enhanced hover and active states for buttons to provide clear feedback to users.
Media Queries Implementation:

Defined breakpoints using media queries to apply specific styles at various screen widths (e.g., 320px, 768px, 1024px) to ensure a consistent experience across different devices.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

https://github.com/user-attachments/assets/fffb6d71-2995-4e52-8bdf-541a4e8106aa

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by ambarmishraa** [comment]
Thank you for giving me the opportunity to contribute to your project sir @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Hey, @ambarmishraa, don't worry you can contribute here, but a small advice.

once i merge the PR, then you can create the issue, after a day or 2 days

that's the only i am saying.

But you can contribute here also.

it's just an instructions provided by organisers for Project Admins.

**Comment by ambarmishraa** [comment]
Thank you sir for such a relief message. I will surely take care of your instruction.

**Comment by vivekvardhan2810** [comment]
And @ambarmishraa Again thank you for contributing to ML Fusion labs.

**Pull request merged**
