### PR TITLE
Fix nav alignment, about section contrast and layout issue. Fixes #59

### LINKED ISSUE #59: Nav Elements Alignment issue and  About section text issue
In header nav elements are not aligned with proper spacing and also the basic things are not designed properly like nav elements have a fixed width, which create problem while screen size is decreasing and designing of elements can be better like they can be rounded not just when they are hovered but in default state rounded will look better.
In about section, back color and text color is not in contrast and because of this the text is not readable easily.
Also the alignment of text and images is not proper in about section.
I can solve all this issues if this issue is assign to me.

### PR DESCRIPTION
**Pull request by Mohitranag18**
Description:
This PR addresses the following issues as outlined in Fixes #59:

-     Navigation Elements:

1. Fixed alignment issues by adjusting the spacing between nav elements.
2.  Removed the fixed width, allowing for better responsiveness across different screen sizes.
3.  Updated the design of nav elements to have rounded corners by default, rather than only on hover, improving the visual appeal.

-     About Section:

1. Enhanced text readability by improving the contrast between the background color and the text color.
2. Adjusted the alignment of text and images for a more balanced layout.

Changes Made:
-     Improved the layout and spacing of nav elements to ensure proper alignment on different screen sizes.
-     Updated CSS to make nav elements rounded by default.
-     Fixed contrast issues in the About section to enhance readability.
-     Realigned text and images in the About section to ensure consistent visual flow.

Before:
before

After:
after

Related Issue:
This PR fixes #59.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Mohitranag18 please resolve the conflicts.

**Comment by Mohitranag18** [comment]
ok sir

**Comment by vivekvardhan2810** [comment]
@Mohitranag18 check the deployment link, the courses section has changed it's not looking good.

image

**Comment by vivekvardhan2810** [comment]
here is that it is looking in the website.

image

**Comment by Mohitranag18** [comment]
I think that is course page I worked on home page

**Comment by vivekvardhan2810** [comment]
@Mohitranag18 All the pages have the same css code, you made the changes to css code, which caused the problem.

Pls check and make the changes.

**Comment by vivekvardhan2810** [comment]
@Mohitranag18 you made the changes in style.css, i think some component was linked to the courses page.

**Comment by Mohitranag18** [comment]
Sir there is nothing similar element in home page and course page except header, how can my changes reflect to course change.

**Comment by vivekvardhan2810** [comment]
@Mohitranag18 okay, Please resolve the conflicts and check the deployment.

**Comment by Mohitranag18** [comment]
conflicts are resolved sir, please review now

**Pull request merged**
