### PR TITLE
Fixing the Whole Course Page 

### PR DESCRIPTION
**Pull request by saismrutiranjan18**
Issue No :- #99

Fixing the Whole Course Page: Updates

1.Improved Layout:
Fixed alignment issues and made the page fully responsive with CSS Grid and Flexbox.

2.Enhanced Course Cards:
Updated card design with hover effects and improved spacing for a cleaner look.

3.Better Navigation:
Made the navbar sticky and added smooth scrolling between sections.

4.Typography & Colors:
Improved fonts for readability and adjusted colors for better contrast.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 pls mention the issue number.

**Comment by saismrutiranjan18** [comment]
> @saismrutiranjan18 pls mention the issue number. And can i close the Previous Pull Request which you have created.

@vivekvardhan2810 Ok

**Comment by saismrutiranjan18** [comment]
@vivekvardhan2810 I mentioned the issue in the description.

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 please wait i will review and add the labels.

**Comment by saismrutiranjan18** [comment]
@vivekvardhan2810 Ok

**Pull request merged**
