### PR TITLE
ADDED THE NEW FONT FOR ALL THE PAGES

### PR DESCRIPTION
**Pull request by HS202022**
## Issues #646

Closes: #646

## Description

https://github.com/user-attachments/assets/e48eb63f-3b24-45b6-bcb6-06f680cad42d

### Summary
ALL THE PAGES GOT A FRESH AND CLEAN LOOK 

### Details
IT CHANGES THE FONT TO ATTRACT USERS 

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@HS202022 can you fix the size of the navbar, the below image the zoom size is of 100%

image

**Comment by HS202022** [comment]
> @HS202022 can you fix the size of the navbar, the below image the zoom size is of 100%, it is only at home page only.
> 
> remaining pages sizes are good.
> 
> image

doing it

**Comment by HS202022** [comment]
@vivekvardhan2810 now check

https://github.com/user-attachments/assets/927809e2-590c-403d-986b-3ef2045c68ee

**Comment by vivekvardhan2810** [comment]
@HS202022 Done.

**Pull request merged**
