### PR TITLE
added more projects in projects.html code

### PR DESCRIPTION
**Pull request by shravya312**
image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@shravya312 pls mention your issue number.

**Comment by shravya312** [comment]
issue number is 108 @vivekvardhan2810

**Comment by shravya312** [comment]
can you give suggestions to my pr @vivekvardhan2810 I will make changes

**Comment by vivekvardhan2810** [comment]
@shravya312 i will check it and give you the suggestions.

**Comment by shravya312** [comment]
okay thanks @vivekvardhan2810

**Pull request merged**
