### PR TITLE
Fix issue #876 : Add icons on contact page

### PR DESCRIPTION
**Pull request by Adityadhiman0**
## Issues Identification

Closes: #876 

### Summary
A brief description of what this pull request does and why it is needed.
This pr will enhance the user inter face.
### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.
Before
Screenshot 2024-10-20 125605
After
Screenshot 2024-10-20 160906

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 make sure to work on other projects also.

**Comment by Adityadhiman0** [comment]
My fork was out dated in previous pr that's why conflict arise before.

**Comment by vivekvardhan2810** [comment]
No problem @Adityadhiman0, Now it is merged.

And make sure to work and contribute on other projects also.

**Comment by Adityadhiman0** [comment]
I want to know how levels work.
Because I got level 2 once and it it now level 1 again.

**Comment by vivekvardhan2810** [comment]
see @Adityadhiman0 it depends on the quality of code, based on the issue and the Decision of PA, whether he should assign him the level 1 or level 2.

this is how the open source works.

**Comment by Adityadhiman0** [comment]
Thank you for you help

**Pull request merged**
