### PR TITLE
Change the Updated Hero Seciton

### PR DESCRIPTION
**Pull request by saismrutiranjan18**
Fix Issue: #99 
I fixed the hero section on the course page by updating the layout and adding new functionality. The changes include:

Search Bar Integration: Added a search bar to allow users to search for all available courses directly from the hero section.

Enhanced Layout: Improved the design and responsiveness of the hero section to provide a more interactive and user-friendly experience.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 pls resolve the conflicts.

**Comment by saismrutiranjan18** [comment]
Which conflicts can you tell me in details, so that i look and solve

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18

image

**Comment by saismrutiranjan18** [comment]
@vivekvardhan2810 Ok

**Comment by saismrutiranjan18** [comment]
@vivekvardhan2810 is the conflict resolved?

**Comment by vivekvardhan2810** [comment]
image

Screenshot 2024-10-05 202835

image

@saismrutiranjan18, it's coming like this while i check the preview, it's not looking good, pls make the changes.

**Comment by saismrutiranjan18** [comment]
okay i'll further do and try to solve your query @vivekvardhan2810

**Comment by saismrutiranjan18** [comment]
should you want to change whole page or only hero section of course page? @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 fix the whole page.

**Comment by vivekvardhan2810** [comment]
it did not look like this before.

**Comment by saismrutiranjan18** [comment]
actually i fix the hero page only at that time okay no problem i'll fix the whole page for you now @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 have you done, as the resolve conflicts are coming.

**Comment by saismrutiranjan18** [comment]
not yet working on the cards @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Okay, @saismrutiranjan18 pls do it as soon as you can, as you can see the conflicts are coming.

image

**Comment by saismrutiranjan18** [comment]
ok @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 have you completed the work. As the conflicts are coming.

pls do it.

**Comment by saismrutiranjan18** [comment]
@vivekvardhan2810 
image

Working on the Card Formatting and integration of photo in the card with some description rather than have some work with footer as well, i try my best and try to complete as soon as possible

**Comment by vivekvardhan2810** [comment]
Yes, @saismrutiranjan18 please complete it as soon as you can, as the issues are coming related to course page, so that's why

**Comment by saismrutiranjan18** [comment]
> Yes, @saismrutiranjan18 please complete it as soon as you can, as the issues are coming related to course page, so that's why, as i am holding the course page related issues so long time and contributors are asking to assign me.

OK @vivekvardhan2810 I try to complete today onwards and try my best

**Comment by saismrutiranjan18** [comment]
> Yes, @saismrutiranjan18 please complete it as soon as you can, as the issues are coming related to course page, so that's why, as i am holding the course page related issues so long time and contributors are asking to assign me.
@Is the card alignment all good and do you want some changes?

**Comment by saismrutiranjan18** [comment]
@vivekvardhan2810 I Completed all things are you there please look all those changes and what you want to change please tell me as soon as possible i make changes accordingly

image

image

image

These are all changes!

**Comment by vivekvardhan2810** [comment]
@saismrutiranjan18 pls resolve the conflicts.

**Comment by saismrutiranjan18** [comment]
> @saismrutiranjan18 pls resolve the conflicts and add the code, then i will review it.

@vivekvardhan2810 Ok

**Pull request closed without merging**
