### PR TITLE
fixed allignment

### LINKED ISSUE #659: fixing alignment issues
hey there 

I noticed that these buttons are not aligned properly and it looks ugly
image

i would like to fix this

assign this to me under gssoc extd , hacktoberfest pleas

### PR DESCRIPTION
**Pull request by aditya07389**
Fixes #659 

Hey @vivekv2810 I have fixed the alignment issues kindly check !!

image
Its properly aligned now !
Thankyou!!
please add the labels : gssoc extd , hacktoberfest and level 2

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
Done @aditya07389 Good.

**Comment by aditya07389** [comment]
Thanks, I also want to work on adding scroll reveal effects , it might look cool, improve the aesthetics

**Comment by vivekvardhan2810** [comment]
@aditya07389 for now we don't require for this.

anyways thank you for contributing to this project.

till then do contribute to other projects also,

**Comment by aditya07389** [comment]
Okay cool

**Comment by RadhikaMalpani1702** [comment]
@mastansayyad can you review this PR

**Comment by vivekvardhan2810** [comment]
@RadhikaMalpani1702 can i reduce the level.

**Comment by aditya07389** [comment]
Is there an issue?

**Comment by vivekvardhan2810** [comment]
@aditya07389 ill it be okay for you, if i give you level 1.

if i assign you level 2 then there will be some issues from my side. as a project admin and program manager reviews all this PR's and it's a clear instruction.

so please understand.

will it be okay for you.

As this PR's and issues are reviewed by program manager.

**Comment by aditya07389** [comment]
Okay I understand, no problem at all!

**Pull request merged**
