### PR TITLE
Increase the responsiveness of featre-grid and newslatter

### PR DESCRIPTION
**Pull request by Hamza20203064**
I cleaned up the HTML page to make it easier for other contributors to read. Additionally, as per issue #10 that I raised, I made the 'Our Features' grid responsive. I also made the 'Contact Us' button responsive for mobile convenience. Please accept my pull request and merge it into the main branch.

There might be a merge conflict as I cleaned the main HTML file, but the core code remains unchanged. Please resolve the conflict and merge it into the main branch.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Hamza20203064 pls resolve the conflicts.

**Comment by Hamza20203064** [comment]
@vivekvardhan2810, please check again

**Comment by Hamza20203064** [comment]
Let me know if there is any issue.

**Comment by vivekvardhan2810** [comment]
@Hamza20203064 pls resolve the conflict, it has raised again.

**Comment by Hamza20203064** [comment]
@vivekvardhan2810 check once again

**Comment by vivekvardhan2810** [comment]
@Hamza20203064 pls resolve the conflicts. I will merge it.

**Comment by Hamza20203064** [comment]
@vivekvardhan2810 this issue arises again and again because I made many changes in html and css file because many contribute use style tag in html and I will turned them to css file.
If you merge other file before my file it will arise this same issue.

**Comment by vivekvardhan2810** [comment]
okay @Hamza20203064 got it, but for now can you resolve the conflicts, i will the merge it by today.

**Comment by Hamza20203064** [comment]
@vivekvardhan2810 I am currently out of station.I don't t have laptop with me. Can we resolve this issue in the morning? Whenever you will be free plz drop a MSG.

**Pull request closed without merging**
