### PR TITLE
add social media icons

### PR DESCRIPTION
**Pull request by pankajsaini1**
i add social media icons in all pages and improve some pages also

### CODE REVIEW

**Comment by pankajsaini1** [comment]
i add social media icon in all pages

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 pls mention your issue number.

**Comment by pankajsaini1** [comment]
> @pankajsaini1 pls mention your issue number.

Adding social media icons to the footer on all pages. #102

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 i didn't assigned you the issue and you have created the PR directly.

**Comment by pankajsaini1** [comment]
> idn't assigned you the issue and you have created th

yes

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 if i have assigned you the issue then only you have to create the PR, else it won't be counted.

**Comment by pankajsaini1** [comment]
> @pankajsaini1 if i have assigned you the issue then only you have to create the PR, else it won't be counted.

 I didn't know about this. can you please assigned it to me.

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 if i will assign this issue to you then there will be the conflicts between the person who has created the issue, then I will have to bare.

**Comment by pankajsaini1** [comment]
> @pankajsaini1 if i will assign this issue to you then there will be the conflicts between the person who has created the issue, then I will have to bare.

ok thanks for guiding me.

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 for now i am closing this PR 

You can look for other issues at website then you can create the new issue.

**Pull request closed without merging**
