### PR TITLE
#4-issue(Fix Navbar)

### PR DESCRIPTION
**Pull request by ezDecode**
Screenshot 2024-10-01 223018
Screenshot 2024-10-01 223027
Screenshot 2024-10-01 222849

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@ezDecode, pls resolve the conflicts.

**Comment by vivekvardhan2810** [comment]
Yes @ezDecode, check

Will.merge it soon.

**Comment by ezDecode** [comment]
Feedback! Is it good?

**Comment by vivekvardhan2810** [comment]
@ezDecode pls mention the issue number, as it will be helpful for me to merge

**Comment by ezDecode** [comment]
How can I add it? Tell me the process.

**Comment by vivekvardhan2810** [comment]
Like mention the issue number like this 

#(issue number)

**Comment by ezDecode** [comment]
Done, check it now!

**Comment by vivekvardhan2810** [comment]
Yes, @ezDecode good, I will check and merge it tomorrow

**Pull request merged**
