### PR TITLE
Enhanced header section for responsiveness and interaction

### PR DESCRIPTION
**Pull request by akshayks13**
1. Improved Layout and Structure:
Rearranged HTML Elements: The nav element now wraps the logo and the navigation links, creating a more organized structure. This helps in aligning the elements properly for both desktop and mobile views.
Logo Alignment: The logo (ML Fusion Labs) has been aligned alongside the navigation links for a cleaner, more balanced appearance. This ensures better visibility and branding at the top of the page.
2. Enhanced Visuals with Hover Effects:
Link Interactions: Navigation links now have a more engaging hover effect. On hover, the text changes color to a bright blue (#00c6ff), and the link slightly enlarges with a subtle scaling effect (transform: scale(1.05)), making it clear to users that the link is interactive.
Background Hover Effect: Added a light blue background behind each link during hover to emphasize the selected link, improving the user experience with better visual feedback.
. Modernized Spacing and Positioning:
Header Padding and Alignment: Improved the spacing around the header elements for better readability and layout consistency. Specifically, added margins to both the logo and navigation links for clearer separation.
Sticky Header: Ensured the header stays fixed at the top of the page when the user scrolls, making navigation more accessible and enhancing the overall user experience.
5. Transition Effects for Smooth Interaction:
Smooth Color and Scale Transitions: Implemented transition effects for both the hover color change and the scaling of links, providing a polished look as users interact with the navigation. This makes the site feel more modern and responsive to user actions.
6. Refined Navigation Menu on Desktop:
Centered Navigation Links: On larger screens, the navigation links are better aligned horizontally, providing a more professional and clean layout.
Increased Readability: Font sizes for the navigation items have been adjusted for clarity (font-size: 16px), ensuring text remains easily readable while still blending well with the overall design of the site.
CSS Refactoring:

Reorganized CSS: Grouped the header-specific styles for easier maintenance and readability. This helps future developers easily find and modify the header styling as needed.
Unified Padding and Margin: Used consistent padding and margin values across the header and navigation items to ensure everything is spaced evenly.

Please add the tags HacktoberFest and GSSOC

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@akshayks13 pls mention the issue number, so that it will be easy for me to check and merge.

**Comment by akshayks13** [comment]
> @akshayks13 pls mention the issue number, so that it will be easy for me to check and merge.

nav bar alignment
Improving the header 
Nav Elements Alignment issue 

I have fixed these issues

**Comment by vivekvardhan2810** [comment]
@akshayks13 okay, I am asking for issue number 

Like is it issue number something

I can't see your issue created.

Pls share the issue number 

#(issue number)

**Comment by akshayks13** [comment]
> @akshayks13 okay, I am asking for issue number
> 
> Like is it issue number something
> 
> I can't see your issue created at issues section.
> 
> If created, Pls share the issue number
> 
> #(issue number)

# nav bar alignment #45
# incomplete alignment in navigation bar + Bug in text area #39
# Nav Elements Alignment issue and About section text issue #59

These are the issue number 

For the issue number 39 and 59 , I have made the changes in the nav section alone

**Comment by aditya-bhaumik** [comment]
@akshayks13 it is not good practice to work on other peoples issue

**Comment by aditya-bhaumik** [comment]
@akshayks13 create your own issue and work on it

**Pull request closed without merging**
