### PR TITLE
updated_directory of workflow

### PR DESCRIPTION
**Pull request by Abhi9shinde**
Sorry For the incovenience.
I have updated the directory

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde i can't see any changes.

you can have this one as reference.

https://github.com/aditya-bhaumik/Pathsphere/tree/main/.github

**Comment by Abhi9shinde** [comment]
sir i have changed the directory path .github/workflow to .github/workflows

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde i am getting like this 

image

**Comment by Abhi9shinde** [comment]
sir please see the missing 's' in workflow of first directory

**Comment by Abhi9shinde** [comment]
yes sir, should i add everything that they have been using

**Comment by Abhi9shinde** [comment]
I'll make the changes write away

**Comment by vivekvardhan2810** [comment]
image

same it should be.

**Pull request closed without merging**
