### PR TITLE
Responsiveness of home Page(issue#410)

### PR DESCRIPTION
**Pull request by Ishika-Singhal**
## Issues Identification

Closes: #410 

### Summary
The home page is made responsive and solve the issue of alignment of newsletter section 

### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [ x] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.
Screenshot (71)

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Ishika-Singhal While i was checking the preview, 

image

the header space is more in desktop.

image

the above image our feature size is less in desktop.

please make the required changes,

**Comment by Ishika-Singhal** [comment]
I have solved the issue of header .The size of header can't reduce more because of the height of logo. 
Also resolve feature section.

**Comment by vivekvardhan2810** [comment]
it should be like the image shown below

image

**Comment by Ishika-Singhal** [comment]
Screenshot (73)

I hope now the header and feature section look perfect.
if there is any issue please tell.

**Comment by vivekvardhan2810** [comment]
@Ishika-Singhal header is good, just make a small change, just a minor change

change the size of Our feature section as mentioned in image below.

image

**Comment by vivekvardhan2810** [comment]
@Ishika-Singhal again the size is increased in features section

Deploy Preview:

image

Actual Website:

image

make the changes as shown in the image of actual website. And check the deploy preview also.

**Comment by Ishika-Singhal** [comment]
Screenshot (75)
I have modified the feature section according to the given size.

**Comment by vivekvardhan2810** [comment]
can you check once again, @Ishika-Singhal because for me deploy preview is looking like this 

image

**Comment by Ishika-Singhal** [comment]
Screenshot (76)

 
I have made more changes to size. And above preview is visible to me

**Comment by vivekvardhan2810** [comment]
Yes, Now it is looking good @Ishika-Singhal, 

Done.

**Comment by Ishika-Singhal** [comment]
Thank you sir!

**Pull request merged**
