### PR TITLE
made changes in the project section's pop-up message- text rendering issue.

### PR DESCRIPTION
**Pull request by synthiaekka**
Fix issue: #194 
I have updated the pop-up message to resolve the text rendering issue, enhancing visibility and overall user experience.

Changes include:

Improved legibility of the text when the 'Learn More' button is clicked.
Ensured that the pop-up close functionality operates correctly.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@synthiaekka 

The Project section looks like this in website right now

image

And When i have checked the preview, it's looking like this.

image

Please make the changes and update it.

**Comment by synthiaekka** [comment]
okay. I'll make the required changes.

**Comment by synthiaekka** [comment]
I've just pushed some updates to this pull request. Please review the changes.

**Comment by vivekvardhan2810** [comment]
@synthiaekka I will check it tomorrow and will let you know.

**Comment by synthiaekka** [comment]
Ok, thanks.

**Comment by vivekvardhan2810** [comment]
@synthiaekka While I was checking the Preview, it's coming like this

image

image

Can You look for the changes and Update it.

**Comment by vivekvardhan2810** [comment]
@synthiaekka it is looking good, but just a minor change, can you create the gap between project to project.

image

**Comment by synthiaekka** [comment]
Sure, no problem.

**Comment by vivekvardhan2810** [comment]
Have you updated it.

**Pull request merged**
