### PR TITLE
Fixed the bug

### LINKED ISSUE #1024: pop up description not matching title
### Description

two new projects added in between

### Steps to Reproduce

projects.html not updated

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Screenshots

https://github.com/user-attachments/assets/cfb4cf62-07b9-42a1-94d6-009b44667484

### Additional Information

_No response_

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
Fixes #1024

## Issues Identification

Closes: #1024 

### Summary
A brief description of what this pull request does and why it is needed.

### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 Thank you for contributing to ML Fusion Labs.

your contribution values to our project.

please do contribute to other projects also.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 any suggestion on ML Fusion Labs and about me also.

would like to know it.

**Comment by DarshAgrawal14** [comment]
> @DarshAgrawal14 any suggestion on ML Fusion Labs and about me also.
> 
> would like to know it.

one major problem i faced during learning ML was that I would ready made algorithms from modules like sci-kit learn , tensorflow etc and if i tried learning working , the given docs were too complex to understand. 
So i had a suggestion that you can add a section where users can find videos and code that imitate working of ML algorithms making user understand the algorithm actually works and grasp it better

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 we are also planning for this.

we have kept this for later.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 and some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.

And how much i was actively working on this.

**Comment by vivekvardhan2810** [comment]
Thank you @DarshAgrawal14 for the compliments and I loved your work also mann.

Damn Good., you are a deemed contributor, Keep Going and all the best. Keep contributing to Open source.

**Comment by DarshAgrawal14** [comment]
You're welcome! I really appreciate the kind words, it means a lot. It's been awesome working in open source, and I’m definitely going to keep at it. Thanks again, and all the best to you too!

**Comment by vivekvardhan2810** [comment]
Thanks a lot @DarshAgrawal14

**Pull request merged**
