### PR TITLE
Revamp privacy and policy page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #907 
Screenshot 2024-10-22 at 2 37 07 AM
Screenshot 2024-10-22 at 2 37 19 AM

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 can you change the footer ones, it should be same as like home page.

can you fix this.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 can you change the footer ones, it should be same as like home page.
> 
> can you fix this.

sure

**Comment by shubhagarwal1** [comment]
hey @vivekvardhan2810 i have fixed the 
Screenshot 2024-10-22 at 2 44 33 AM
footer please review

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 just one small change please.

image

can you add the gap.

as it should look like this

image

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1

**Comment by shubhagarwal1** [comment]
sure let me do it

**Comment by shubhagarwal1** [comment]
Screenshot 2024-10-22 at 3 00 47 AM
fixed 
hey @vivekvardhan2810 so Sorry fo the minor errors

**Comment by vivekvardhan2810** [comment]
No Problem @shubhagarwal1 

> Screenshot 2024-10-22 at 3 00 47 AM fixed hey @vivekvardhan2810 so Sorry fo the minor errors

**Comment by vivekvardhan2810** [comment]
Done @shubhagarwal1.

Good Work and Good Job.

**Review by vivekvardhan2810 — APPROVED** [review]

**Pull request merged**
