### PR TITLE
Twitter logo changed to x

### PR DESCRIPTION
**Pull request by raushan2104**
issue #140 

twitter logo changed

### CODE REVIEW

**Comment by raushan2104** [comment]
@vivekvardhan2810 sir check this pr

**Comment by vivekvardhan2810** [comment]
@raushan2104 while i was checking preview

In home page:

image

i can't see X symbol

and it is in same case for remaining pages, please check the deploy preview and update it.

**Comment by raushan2104** [comment]
@vivekvardhan2810 sir w8

**Comment by raushan2104** [comment]
@vivekvardhan2810 see again

**Comment by vivekvardhan2810** [comment]
@raushan2104 now it is coming, right now i am in sleep , i will check and merge it tomorrow.

**Pull request merged**
