### PR TITLE
Built `Programming And Development` ; and `Artificial Intelligence` Page

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
Closes: #819

## Description

- Built `Programming And Development` ; and `Artificial Intelligence` Page as mentioned in the issue.
- similar to data science essential card

@vivekvardhan2810 please review it
## Types of Changes

 - [x] New feature (non-breaking change that adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Video

https://github.com/user-attachments/assets/d99cb9bb-f584-423d-9bf7-accfefcc0f05

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
Done @Adarsh-Chaubey03.

Good.

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 can you do a task for me.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 can you do a task for me.

Sure

**Comment by vivekvardhan2810** [comment]
can we communicate it through Linkedin @Adarsh-Chaubey03 

I have connected you.

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 accept my connection in linkedin

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 accept my connection in linkedin

Did it

**Pull request merged**
