### PR TITLE
Website Footer Modification and README Updation

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
## Issues Identification

Closes: #740 

### Summary

Added **Hover animation** on the Social Icons of the Footer section and added a **Team Section** in the README.md file

### Details

1. Footer Section:

I have modified the following:

- Added: **Zoom on hover** on the Social Icons.
- Added: **Color Change on hover** on the Social Icons.
- Centred and Enlarged the **Copyright section** for better visibility.

3. Team Section:

Added a **Team Section** for contributors to reference, helping them know whom to contact if they encounter any difficulties.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] My changes do not break the current system and pass all existing test cases
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Screenshots/Videos

- Footer Section:

https://github.com/user-attachments/assets/1ffa9891-713d-4183-8349-ccf5b9b9add6

- Team Section:
image

## Additional Information

Please review the PR and assign it to me with the necessary labels.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for reviewing the PR. Hope you have a great day ahead!

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc Good Work and Good Job.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Good Work and Good Job.

Thanks for the appreciation

**Comment by vivekvardhan2810** [comment]
> Thanks for reviewing the PR. Hope you have a great day ahead!

Thank you @rajdeepchakraborty-rc for contributing to ML Fusion Labs. Hope you have a great day ahead!

**Pull request merged**
