### PR TITLE
#804 The about section is not responsive

### PR DESCRIPTION
**Pull request by ambarmishraa**
#804 (The about section is not responsive.)

Closes: #804 (The about section is not responsive.)

## Description
The about section was not responsive on mobile devices, so i fixed it by setting the width of the footer which was causing the error.
### Summary
This pull request addresses the issue where the "About" section was not responsive on mobile devices. The width of the footer was adjusted to ensure proper scaling and responsiveness on smaller screens.

### Details
- Set the width of the footer to ensure it no longer interferes with the responsiveness of the "About" section.
- Verified that the section now adapts correctly to different screen sizes, especially mobile devices.

## Types of Changes

_Please check the boxes that apply_

- [X] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Screenshots
Before : Screenshot 2024-10-18 230226

After : 
https://github.com/user-attachments/assets/39b4d93b-a2ec-4bb4-92ae-60ad6b72b163

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@ambarmishraa can you share the video recording, so that i can look on it.

**Comment by ambarmishraa** [comment]
@vivekvardhan2810 You can verify the changes and let me know if you need further changes.

**Comment by ambarmishraa** [comment]
This is really amazing project, i will love to work further on it .Thank you @vivekvardhan2810 for the opportunity.

**Comment by vivekvardhan2810** [comment]
@ambarmishraa and also do work for other projects also.

And also this project will be active till October 27th, after that I won't be active and the project also.

**Comment by ambarmishraa** [comment]
That's a lot of time for me.. I will surely contribute something cool before that. @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@ambarmishraa Wishing you all the best and keep contributing to open source and other projects also.

**Comment by ambarmishraa** [comment]
I will surely do that too sir.

**Pull request merged**
