### PR TITLE
add email page and recorrected link to all pages

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #997

Screenshot 2024-10-25 at 12 40 40 AM

Hey @vivekvardhan2810 please review my PR

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 while i was checking the deploy preview in email page.

i can't see the logo

image

and here also.

image

please make the required changes.

**Comment by shubhagarwal1** [comment]
> fix: #997
> 
> Screenshot 2024-10-25 at 12 40 40 AM
> Hey @vivekvardhan2810 please review my PR

Hey @vivekvardhan2810 this PR has many code lines changes, it is jsut because of reformatiing 
also i have chagned the email us link to all the pages 
and updated it so, no worries code is tight and okay

**Comment by shubhagarwal1** [comment]
Doing, logo fix

**Comment by shubhagarwal1** [comment]
Hey @vivekvardhan2810 done logo fix

**Comment by vivekvardhan2810** [comment]
Done @shubhagarwal1.

Updating the level also.

**Review by vivekvardhan2810 — APPROVED** [review]

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.

And how much i was actively working on this.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 Can you share some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.
> 
> And how much i was actively working on this.

Working with @vivekvardhan2810  as a project admin and contributor has been an absolute pleasure. You were incredibly active on the repo, consistently reviewing the valuable insights and solutions, your dedication to the project was evident through his prompt responses, well-organized tasks, and proactive approach to resolving issues. His collaborative nature made the development process smooth and efficient, and I truly appreciated your commitment and hard work throughout the project, thankyou for the opportunity, and again working with you.

**Comment by shubhagarwal1** [comment]
and bhai @vivekvardhan2810 agr ho ske can i have your contact details like number or linkedin

**Comment by vivekvardhan2810** [comment]
> Working with @vivekvardhan2810 as a project admin and contributor has been an absolute pleasure. You were incredibly active on the repo, consistently reviewing the valuable insights and solutions, your dedication to the project was evident through his prompt responses, well-organized tasks, and proactive approach to resolving issues. His collaborative nature made the development process smooth and efficient, and I truly appreciated your commitment and hard work throughout the project, thankyou for the opportunity, and again working with you.

Thank you @shubhagarwal1 for the compliments and I loved your work also mann.

Damn Good., you are a deemed contributor, Keep Going and all the best. Keep contributing to Open source.

**Comment by vivekvardhan2810** [comment]
> and bhai @vivekvardhan2810 agr ho ske can i have your contact details like number or linkedin

You can check my linkedin in my profile.

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 Thank you for contributing to ML Fusion Labs.

your contribution values to our project.

please do contribute to other projects also.

And wishing you all the best for your future endeavors.

**Review by MastanSayyad — COMMENTED** [review]
Hi @vivekvardhan2810 reduce the levels for this PR to `level 2`, most of the code is formatted

**Comment by vivekvardhan2810** [comment]
Okay @MastanSayyad.

**Pull request merged**
