### PR TITLE
Add Dark/Light Mode Toggle with Custom Icons

### PR DESCRIPTION
**Pull request by Manojkumar2806**
Implemented a toggle switch to enable dark and light mode across the website for enhanced user experience.

Added visually appealing custom icons for dark (moon) and light (sun) modes.

Integrated smooth transition effects when switching between modes.

Ensured that the theme preference is saved in local storage, so the user's choice persists across sessions.

Tested for responsiveness and compatibility on various devices.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Manojkumar2806 please mention your issue number.

i didn't assigned you the issue.

**Comment by vivekvardhan2810** [comment]
@Manojkumar2806 i didn't assigned you the issue, and you have created direct Pull Request.

This is not a Good Open Source Practice.

So I am Closing the Pull Request.

Until I assign the issue no one should create or commit the pull request.

please understand.

Please follow the gssoc guidelines properly

This is an open source and Everyone deserves equal opportunity.

**Comment by Manojkumar2806** [comment]
I apologize  for that  i am begginer with open source.

Could you please help me how to make the pull request ( without direct pull
request )

**Comment by vivekvardhan2810** [comment]
first of all you need to create an new issue

then you have to wait to for the project admin assigning you the issue.

if it is unique he will assign you, then only you have to create pull request.

if he closes the issue, then it means it is no longer need.


@Manojkumar2806 i didn't assigned you the issue, and you have created direct Pull Request.

This is not a Good Open Source Practice.

So I am Closing the Pull Request.

Until I assign the issue no one should create or commit the pull request.

please understand.

Do follow the gssoc guidelines properly

This is an open source and Everyone deserves equal opportunity.

**Comment by Manojkumar2806** [comment]
Is my issue already created ??

**Comment by Manojkumar2806** [comment]
It is not created please assign to me ??

**Comment by vivekvardhan2810** [comment]
you have to create a new issue, and the dark and light toggle mode was already there in website, so please look for other issues in website, then create new issue.

And please do contribute to other projects also, it's a request.

**Comment by Manojkumar2806** [comment]
Ok, I will try.

**Pull request closed without merging**
