### PR TITLE
Updated footer design

### PR DESCRIPTION
**Pull request by akshattiwarii**
## Issues Identification

Closes: #713 

### Summary
Updated footer design in all the pages with responsive as well as fit according to the theme as per user selected.

### Details
- Before:
Screenshot 2024-10-17 003627

- After:
Screenshot 2024-10-17 003537

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] My changes do not break the current system and pass all existing test cases
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Screenshots

Screenshot 2024-10-17 003537

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@akshattiwarii please resolve the conflicts.

**Comment by akshattiwarii** [comment]
> @akshattiwarii please resolve the conflicts.
> 
> image

Yes, please wait I am trying to solve this !

**Comment by akshattiwarii** [comment]
sir done !

**Comment by vivekvardhan2810** [comment]
image

i can't see the logo in remaining pages.

i can only see the logo in home page.

can you look the deploy preview and check it.

**Comment by akshattiwarii** [comment]
> image
> 
> @akshattiwarii i can't see the logo in remaining pages.
> 
> i can only see the logo in home page.
> 
> can you look the deploy preview and check and update it.

but I can see the logo in different pages also 
Screenshot 2024-10-17 005247

**Comment by vivekvardhan2810** [comment]
Okay, Done @akshattiwarii Good Work.

**Pull request merged**
