### PR TITLE
ADDED THE FEATURE OF LANGUAGE TRANSLATION

### PR DESCRIPTION
**Pull request by HS202022**
ISSUE #550

Closes: #550

## Description

https://github.com/user-attachments/assets/dcadcdda-fdda-445b-b1b7-f73cdefdfea7

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@HS202022 While checking the preview, the navbar is looking like this

image

please check the preview once and then update it.

**Comment by HS202022** [comment]
> @HS202022 While checking the preview, the navbar is looking like this
> 
> image
> 
> please check the preview once and then update it.

https://github.com/user-attachments/assets/69235141-414e-4c3b-a239-bc8497d150a4

**Comment by HS202022** [comment]
> > @HS202022 While checking the preview, the navbar is looking like this
> > image
> > please check the preview once and then update it.
> 
>  Untitled.video.-.Made.with.Clipchamp.24.mp4

its working fine

**Comment by vivekvardhan2810** [comment]
@HS202022 But, Again it is coming like this from my side😭😭

image

**Comment by HS202022** [comment]
> @HS202022 But, Again it is coming like this from my side😭😭
> 
> image
> 

I think it was from before let me show you

**Comment by vivekvardhan2810** [comment]
image

this one is coming at zoom 90% size

**Comment by vivekvardhan2810** [comment]
But at Zoom 100% size

image

**Comment by HS202022** [comment]
> But at Zoom 100% size
> 
> image


https://github.com/user-attachments/assets/46076603-8279-4561-b0c3-f6863f46b951

**Comment by vivekvardhan2810** [comment]
@HS202022 let's do one thing can you make it normal for all the sizes with gaps presented.

**Comment by HS202022** [comment]
> @HS202022 let's do one thing can you make it normal for all the sizes with alignment shall be uniform.

fine

**Comment by HS202022** [comment]
> > @HS202022 let's do one thing can you make it normal for all the sizes with alignment shall be uniform.
> 
> fine

please mark level 3 i will fix this for sure

**Comment by vivekvardhan2810** [comment]
@HS202022 I will mark it as level 3 for sure.

**Comment by vivekvardhan2810** [comment]
@HS202022 Done, marked as level 3, fix this.

**Comment by HS202022** [comment]
@vivekvardhan2810 check this now

**Comment by vivekvardhan2810** [comment]
@HS202022 Now, it is looking good.

Done.

Good Work.

**Comment by vivekvardhan2810** [comment]
@HS202022 can you send the video proof, so that i can check and merge it.

**Comment by HS202022** [comment]
> @HS202022 can you send the video proof, so that i can check and merge it.


https://github.com/user-attachments/assets/9d018439-8c1d-4299-9e20-008250850c5d

**Comment by HS202022** [comment]
thank you i can work for other issues too if it remains unsolved

**Comment by vivekvardhan2810** [comment]
@HS202022 i will let you know, till then you can contribute to other projects.

**Pull request merged**
