### PR TITLE
Redesign newsletter

### PR DESCRIPTION
**Pull request by ArchanRD**
## Issues Identification

Closes: #839 

### Summary
Redesigned the newsletter with better look.

### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

### BEFORE
image

### AFTER
image

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@ArchanRD this design is not looking good

image

the box is linking with footer one's which is not looking good.

please make the required changes.

**Comment by ArchanRD** [comment]
@vivekvardhan2810 How about this?
image

**Comment by vivekvardhan2810** [comment]
@ArchanRD design is good, but the outer box of newsletter is linking with footer one's which is not looking good

like this.

image

**Comment by ArchanRD** [comment]
@vivekvardhan2810 Okay I though it would look good connected to footer. Let me do that change as well and push!

**Comment by ArchanRD** [comment]
Please have a look now!

**Comment by vivekvardhan2810** [comment]
Done @ArchanRD. 

Good.

**Pull request merged**
