### PR TITLE
navbar updated

### PR DESCRIPTION
**Pull request by Parthmagdum**
## Issues Identification

Closes: #232 

## Description
improvisation in theme changer button 
### Screenshots

**Dark Mode**
image

**Light mode**
image

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Parthmagdum I am closing this PR, as I didn't assigned you the issue and you have directly created the Pull request

This is not a good practice.

**Comment by Parthmagdum** [comment]
I am New in open source contribution, So you tell what should I do.

**Comment by vivekvardhan2810** [comment]
@Parthmagdum please the issue guidelines pinned at issues section, then you can understand. And when you have created a new issue, you have to wait untill the issue is assigned, if it is assigned, then you have to commit and Create the new Pull Request.

**Comment by Parthmagdum** [comment]
@vivekvardhan2810 Okay Thank you for your help.

**Pull request closed without merging**
