### PR TITLE
Added feature: the testimonial Section

### PR DESCRIPTION
**Pull request by AasthaSingh28**
## Issues Identification

Closes: #386

## Description
Added the testimonial section in home page. Made the page using HTML and styled it using bootstrap.

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Screenshots

image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@AasthaSingh28 please resolve the conflicts.

**Comment by AasthaSingh28** [comment]
@vivekvardhan2810 ✅ resolved conflicts..

**Comment by vivekvardhan2810** [comment]
@AasthaSingh28 while i was checking the preview, it's coming like this

image

and you have changed the font.

there is a separate section of testimonial, you can update there

click community support page, there you can find testimonial section.

image

if you want you can improve in that section.

image

**Comment by vivekvardhan2810** [comment]
@AasthaSingh28 will it be okay for you, if i close this PR, so that you can update it.

**Comment by AasthaSingh28** [comment]
@vivekvardhan2810 ok sure

**Pull request closed without merging**
