### PR TITLE
ContactUs page updated

### LINKED ISSUE #521: [Contact us page ]: update the contact Us page
### Is your feature request related to a problem? Please describe.

1. More cleaner
2. Using nicer UI

### Describe the solution you'd like.

I would like to create a better UI for contact us page

### Describe alternatives you've considered.

_No response_

### Additional context.

_No response_

### Show us the magic with screenshots

Screenshot 2024-10-13 021658
Screenshot 2024-10-13 021723

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by eshaalal**
I have updated the contact us page 

Closes #521

Before :

Screenshot 2024-10-13 152824

After :

https://github.com/user-attachments/assets/081a5e80-029e-416b-ab30-ae77386cacc6

Screenshot 2024-10-13 153151

****  Do let me know if something needs to be changed  ****

### CODE REVIEW

**Comment by eshaalal** [comment]
@ML-Fusion-Lab please have a look into it and let me know what needs to be added

**Comment by vivekvardhan2810** [comment]
@eshaalal can you add the dark and light mode toggle button on the page, and update it.

**Comment by eshaalal** [comment]
@ML-Fusion-Lab kindly merge the PR and assign me the appropriate label (Level 2). You can assign the toggling feature to me in another issue raised.

**Comment by eshaalal** [comment]
and would really appreciate if you give me hacktoberfest-accepted for this PR

**Comment by vivekvardhan2810** [comment]
@eshaalal please mention the issue number.

**Pull request merged**
