### PR TITLE
Correctly added workflow

### PR DESCRIPTION
**Pull request by Abhi9shinde**
Correctly added workflow.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde replace the pathsphere repo link with this link

https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde i will check and update it.

**Comment by Abhi9shinde** [comment]
#367

**Comment by Abhi9shinde** [comment]
Thank you so much for your help and guidance! 🙌 I really appreciate your help on this project.

**Pull request merged**
