### PR TITLE
add FAQs section to Footer

### PR DESCRIPTION
**Pull request by devxMani**
## Issues Identification

Closes: #(#19 )

### Summary
A brief description of what this pull request does and why it is needed.

### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@devxMani can you share the screenshot of where can i see the FAQ section.

**Comment by devxMani** [comment]
@vivekvardhan2810 
image

**Comment by devxMani** [comment]
its also correctly alligned

**Comment by vivekvardhan2810** [comment]
@devxMani  as i can see only 1 file change.

if i assign you level 2 then there will be some issues from my side. as a project admin and program manager reviews all this PR's and it's a clear instruction.

so please understand.

As this PR's and issues are reviewed by program manager.

so that's why

will it be okay for you if i give this in level 1.

**Comment by vivekvardhan2810** [comment]
@devxMani one more thing 

i was checking the deploy preview.

while i was checking for dark mode.

it is looking like this.

image

can you make some changes to it.

**Comment by devxMani** [comment]
@vivekvardhan2810 check its working 
image

**Comment by vivekvardhan2810** [comment]
Done @devxMani.

Merging this.

Thank you for contributing to ML Fusion Labs.

your contribution values to our project.

please do contribute to other projects also.

And wishing you all the best for your future endeavors.

**Comment by vivekvardhan2810** [comment]
@devxMani Can you share some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.

And how much i was actively working on this Project.

Any suggestions.

**Review by vivekvardhan2810 — APPROVED** [review]

**Comment by devxMani** [comment]
@vivekvardhan2810 I have made all the changes in only the HTML file and added styles also in the HTML file I think its okay for level 2

**Comment by devxMani** [comment]
@vivekvardhan2810 it was great working with you, your role as admin is commendable and easygoing

**Comment by vivekvardhan2810** [comment]
No problem @devxMani , same here also but i want to pursue my higher studies.

so i too have exams.

so that's why i am being inactive from 26th.

**Comment by devxMani** [comment]
@vivekvardhan2810 those things are more imp than these

**Comment by vivekvardhan2810** [comment]
yes @devxMani.

**Pull request merged**
