### PR TITLE
Added `QnA Section` in Community Part

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
Closes: #461

## Description

Added following features :
- latest QnA video 
- Previous week QnA video section
- Guidelines
- Ask your question
- Next Event
- last week FAQs

(keeping footer header intact )
@vivekvardhan2810 please review this
## Types of Changes

_Please check the boxes that apply_

- [x] New feature (non-breaking change that adds functionality)

## Checklists

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

Screenshot 2024-10-12 115438
Screenshot 2024-10-12 115443

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 

while i was checking the preview,

image

heading is different actual heading should be different.

and the page is looking dull

image

please make the required changes,

**Comment by Adarsh-Chaubey03** [comment]
ok

**Comment by Adarsh-Chaubey03** [comment]
Can you please tell .. what heading are you talking of ? Is it header or Heading of boxes or something else?

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 

i am talking about this

image

just replace the word mentor to Q & A

**Pull request merged**
