### PR TITLE
Enhance Navbar, Add Animations, and Improve Responsiveness

### PR DESCRIPTION
**Pull request by Ashish2k03**
Fixed the position of navbar elements for better layout.
Added a hamburger icon for improved mobile navigation.
Implemented animations for the main text on the landing page and navbar elements.
Made the features section fully responsive across different screen sizes.
Improved overall mobile experience and user interaction with the navigation and page elements.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
image

@Ashish2k03 

can you solve this entirely once it is coming like this.

**Comment by vivekvardhan2810** [comment]
@Ashish2k03 

Please resolve the conflicts 

image

Check the above image why is it coming like this and update it.

**Comment by Ashish2k03** [comment]
> @Ashish2k03 
> 
> image
> 
> image
> 
> image
> 
> Check the above image why is it coming like this and pls update it.

What was really going on, i am really confused how does this happens but don't worry I'll be back soon with the new update

**Comment by vivekvardhan2810** [comment]
Okay @Ashish2k03, take your time and update it.

**Comment by Ashish2k03** [comment]
> Okay @Ashish2k03, take your time and update it.

Screenshot 2024-10-02 114340
Screenshot 2024-10-02 114355

**Comment by Ashish2k03** [comment]
> Okay @Ashish2k03, take your time and update it.

Sir something is happened between after it uploaded on netlify itself

**Comment by vivekvardhan2810** [comment]
@Ashish2k03 let's do one thing i am closing this pull request now.

You can create a new PR after updating then it will be good., will it be okay for you.

**Comment by Ashish2k03** [comment]
> @Ashish2k03 let's do one thing i am closing this pull request now.
> 
> You can create a new PR after updating then it will be good. will it be okay for you. (I am saying this because it will be good for avoiding conflicts).
> 
> I will merge that new PR.
> 
> will it be okay for you. @Ashish2k03

okay!

**Comment by Ashish2k03** [comment]
> @Ashish2k03 let's do one thing i am closing this pull request now.
> 
> You can create a new PR after updating then it will be good. will it be okay for you. (I am saying this because it will be good for avoiding conflicts).
> 
> I will merge that new PR.
> 
> will it be okay for you. @Ashish2k03 

Sir please check your linkedin, i send you the message

**Pull request closed without merging**
