### PR TITLE
About us page is complete

### LINKED ISSUE #9: Re-designing of About us page
1st

The About Page re-design focuses on providing a clear, welcoming introduction to your open-source project while offering essential information about your vision, team, and what the project offers. It includes a streamlined layout that highlights the project’s goals, core values, and key features, alongside an easy-to-navigate section for contact details

### PR DESCRIPTION
**Pull request by Amarjeetkumart**
I have completed my work from re-designing of About us page and added a some features  

close #9  

Screenshot from 2024-10-02 04-09-40

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Amarjeetkumart pls resolve the conflicts.

**Comment by vivekvardhan2810** [comment]
@Amarjeetkumart I will check and merge your PR by today.

**Comment by vivekvardhan2810** [comment]
@Amarjeetkumart While i was checking the preview it is coming like this

image

About us page is good, but pls check the above image and resolve this.

**Comment by Amarjeetkumart** [comment]
### sir why we are not able to redirect at about us page on directly clicking at Deployed link Above, its suggesting to re-click at about us page and i don't know to resolve it and i don't see any kinds of conflict at my base branch?

##### sir help me, i am new at this things...

WhatsApp Image 2024-10-03 at 10 49 29 PM

Deploy preview

WhatsApp Image 2024-10-03 at 10 48 15 PM

Final preview
Screenshot from 2024-10-03 22-32-47

**Comment by vivekvardhan2810** [comment]
Okay @Amarjeetkumart I will look into it, Check it and merge it.

**Comment by vivekvardhan2810** [comment]
@Amarjeetkumart please check the home page navbar, you can check my website link and the deployment link.

**Comment by vivekvardhan2810** [comment]
@Amarjeetkumart pls resolve the conflicts.

**Pull request merged**
