### PR TITLE
responsiveness of homepage

### PR DESCRIPTION
**Pull request by Palmistry2310**
## Issues Identification

Closes: #803 

## Description
Made home page responsive.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe): responsiveness

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Screenshots

https://github.com/user-attachments/assets/18068dfb-50a0-4399-86a8-0d0079f39406

## Additional Information

Please provide any other information that is relevant to this pull request.

@vivekv2810 please review this pr.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 thank you for contributing to ML Fusion Labs.

your contribution values to our project.

please do contribute to other projects also.

from tomorrow this project and I will be inactive.

I hope you understand.

**Comment by Palmistry2310** [comment]
@vivekvardhan2810 sir you actually assigned me the level 2 for this issue but now level 1 given!!?

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 as i can see 2 file changes.

if i assign you level 2 then there will be some issues from my side. as a project admin and program manager reviews all this PR's and it's a clear instruction.

so please understand.

will it be okay for you.

As this PR's and issues are reviewed by program manager.

so that's why

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 But again thank you for contributing to ML Fusion Labs.

your contribution values to our project.

please do contribute to other projects also.

from tomorrow this project and I will be inactive.

**Pull request merged**
