### PR TITLE
improved scrolling and added back to top button on feedback page

### PR DESCRIPTION
**Pull request by ananyag309**
## Issues Identification

Closes: #574 

### Summary
improved scrolling and added back to top button on feedback page

### Details
Include any detailed information about the changes in this pull request.

1. Added a back-to-top button
2. Added CSS styles for the back-to-top button
3. Added JavaScript functions to control the button's visibility and scrolling behavior

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

image

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@ananyag309 while i was checking the preview,

image

i can't see scroll up button.

can you check the deploy preview once.

**Comment by ananyag309** [comment]
@vivekvardhan2810 its working did you scroll down? then it will appear

**Comment by vivekvardhan2810** [comment]
yes, @ananyag309 now it is working.

Good.

**Comment by ananyag309** [comment]
(please ignore the low quality of video)
https://github.com/user-attachments/assets/1474dfb3-ecaa-4259-92c6-3e03ef95ac2d

**Comment by vivekvardhan2810** [comment]
@ananyag309 Done.

**Pull request merged**
