### PR TITLE
Implemented a Mini Chatbot

### PR DESCRIPTION
**Pull request by DivyaJyothi9**
## Issues Identification
I have created the PR https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/pull/236 ..for the issue https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues/186 that was assigned to me.

## Description
This issue involves the development of a mini chatbot for the platform. The chatbot will provide users with an interactive experience, helping them explore ML courses, hands-on projects...

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots
Screenshot (312)

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 pls resolve the conflicts.

**Comment by DivyaJyothi9** [comment]
Implement a Mini Chatbot for this website #186 raised a PR #236
kindly assign Gssoc extd, Hactoberfest and lavel-3

Thank you @vivekvardhan2810

**Comment by DivyaJyothi9** [comment]
> @DivyaJyothi9 pls resolve the conflicts.

Just now resolved sir,kindly check it.
Thank you

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 can you pls share the screenshot in which you have implemented.

**Comment by DivyaJyothi9** [comment]
> @DivyaJyothi9 can you pls share the screenshot in which you have implemented.

@vivekvardhan2810 code files or final chatbot which was embedded in website?

**Comment by DivyaJyothi9** [comment]
@vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 the conflicts have arised, pls resolve it and check the deployment preview.

**Comment by DivyaJyothi9** [comment]
@vivekvardhan2810 sir, Kindly check it now!!

**Comment by DivyaJyothi9** [comment]
@vivekvardhan2810 kindly assign the labels--Gssoc-extd, Hactoberfest accepted and Level 3

Thank you

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 it's coming like this 

image

chatbot is near adjacent to scroll bar button,

Can you update that

image

And you can check the above image it's coming like this, pls update that also.

**Comment by DivyaJyothi9** [comment]
@vivekvardhan2810 should I make chatbot to move little above from it?

**Comment by vivekvardhan2810** [comment]
yes.

**Comment by DivyaJyothi9** [comment]
@vivekvardhan2810 can u assign the labels please.

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 i will assign the labels, once you have made changes.

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 have you done.

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 in home page i can't see the chatbot icon, whereas i can see it in remaining pages.

image

**Comment by vivekvardhan2810** [comment]
Yes, Now it is coming. @DivyaJyothi9, Good.

**Comment by DivyaJyothi9** [comment]
yes sir,,i have checked it...now it's visible..u can check it now @vivekvardhan2810

**Comment by DivyaJyothi9** [comment]
Thank you @vivekvardhan2810

**Pull request merged**
