### PR TITLE
[Enchancement] Card Bug and Improved Project Button Functionality

### LINKED ISSUE #641: Wrong Card Appears After Clicking the "Learn More" Button at Project Page
### Description

When clicking the "Learn More" button on the project page, the wrong project card appears in certain instances. This leads to confusion for users, as the displayed content does not match the selected project.

### Steps to Reproduce

1. Navigate to the project page.
2. Click on the "Learn More" button for any project.
3. Observe that the wrong project card is displayed in some cases.

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Screenshots

https://github.com/user-attachments/assets/b6aa8912-b689-46ff-beed-eabf85e104fa

### Additional Information

_No response_

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Description:
- Fixed a bug where the wrong model was appearing after clicking on the project card.
- Improved the project button functionality by adding two separate buttons:
  - "Open Project" for available projects.
  - "Learn More" for projects that are not yet available.

### Changes:
1. **Bug Fix:**
   - Corrected the issue where clicking on the "Show Project" button displayed the wrong project card. The card now properly corresponds to the selected project.
   
2. **Button Enhancement:**
   - Added a "Open Project" button for projects that are currently available, enabling users to view the full project details.
   - Added a "Learn More" button for projects that are not yet available, guiding users to additional information or updates.

### Testing:
- Tested clicking on "Open Project" for multiple projects to redirect  to project page.
- Verified that the "Learn More" button open the model of information.

### Impact:
- Improved user experience by ensuring the correct project details are shown.
- Provided clear navigation for both available and upcoming projects.

### Related Issue:
- Fixes #641

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@IkkiOcean assigned you the level.

**Comment by IkkiOcean** [comment]
> @IkkiOcean assigned you the level.
> 
> can i update the level.

yes please

**Comment by Hemu21** [comment]
@MastanSayyad

**Comment by vivekvardhan2810** [comment]
@MastanSayyad

Please tell me which level can i change to this.

**Comment by vivekvardhan2810** [comment]
@MastanSayyad i have changed the level.

please check it.

**Pull request merged**
