### PR TITLE
Updated dark and light theme mode 

### PR DESCRIPTION
**Pull request by STDYGIT**
sir
as you desire the mode for dakr and light theme been updated have a look

### CODE REVIEW

**Comment by STDYGIT** [comment]
Issue number #105

**Comment by vivekvardhan2810** [comment]
@STDYGIT I will check and merge it by today.

**Comment by STDYGIT** [comment]
sir you have not merged yet??

**Comment by vivekvardhan2810** [comment]
@STDYGIT Jatin I will merge it by today, Pls wait, I will Promise you that it will be done today.

**Pull request merged**
