### PR TITLE
Adding HomeButton to Projects and About Us Pages

### PR DESCRIPTION
**Pull request by umar-farooq-shaik**

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik please mention the issue number.

**Comment by umar-farooq-shaik** [comment]
#1113 Adding HomeButton to Projects and About Us Pages

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik i have asked you to change only the about us page and project page, why did you updated the organisation file structure.

please check this.

and one more thing can we have a meet on it.

so that i can tell you.

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik can we have a google meet now.

so that i can tell you the changes.

**Comment by umar-farooq-shaik** [comment]
ok

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik join with this link.

https://meet.google.com/vcu-gwhh-zgy

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik join with this link, Fast.

https://meet.google.com/vcu-gwhh-zgy

**Comment by vivekvardhan2810** [comment]
brother pls join with the above google link meet fast please.

**Pull request closed without merging**
