### PR TITLE
Fix issue #796 : Toggle switch appearance

### PR DESCRIPTION
**Pull request by Adityadhiman0**
## Issues Identification

Closes: #796 

### Summary
A brief description of what this pull request does and why it is needed.
This pr is needed because before toggle switch appeared same on dark mode as well as light mode, but after this pr toggle switch will appear according to the website theme.
### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

https://github.com/user-attachments/assets/a5e7efb1-d2f3-4129-b9bf-6c91e5ed3208

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 hey, while  I was checking the preview, i can see the toggle ones only in home page, i can't see this in remaining pages.

Can you check the deploy preview and update it in all pages.

**Comment by vivekvardhan2810** [comment]
Good Work @Adityadhiman0.

Done.

**Comment by Adityadhiman0** [comment]
Now, I fix the issue for complete website and commit it in my fork.
Should I create a new pr. Please help me.

**Comment by Adityadhiman0** [comment]
Thank you very much.

**Comment by vivekvardhan2810** [comment]
No need @Adityadhiman0.

your work is done.

**Comment by vivekvardhan2810** [comment]
Anyways Good work @Adityadhiman0.

Wishing you all the best and keep contributing to open source.

**Pull request merged**
