### PR TITLE
fixed #120 : Add Clickable Link to Logo Redirecting to Home Page #120

### LINKED ISSUE #120: Feat: Add Clickable Link to Logo Redirecting to Home Page
Description:
The website logo in the header should be clickable and redirect users to the Home page. This functionality will improve navigation and user experience, allowing users to easily access the main page from any part of the website.

Steps to Reproduce:
1. Visit any page on the website.
2. Try clicking the logo in the navigation bar.
3. Notice that the logo is not linked to the Home page.

Expected Behavior:
When the user clicks on the logo, they should be redirected to the Home page.

Actual Behavior:
The logo is not clickable and does not link to any page.

mllabs

### PR DESCRIPTION
**Pull request by HarshadaGirase**
Fixes #120

Description:

This PR implements a feature that adds a clickable link to the logo, allowing users to easily navigate back to the home page from any section of the platform. This improves user experience by providing a quick and intuitive way to return to the main landing page.

Screenshot (346)

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@HarshadaGirase pls resolve the conflicts.

**Comment by vivekvardhan2810** [comment]
@HarshadaGirase pls resolve the conflicts.

**Comment by HarshadaGirase** [comment]
Sure

**Comment by HarshadaGirase** [comment]
Sure

**Comment by HarshadaGirase** [comment]
@vivekvardhan2810 I resolved the conflicts.

**Comment by vivekvardhan2810** [comment]
Done @HarshadaGirase .

**Pull request merged**
