### PR TITLE
✨Code refactored✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
removed inline CSS as it makes code's readability poor.
This has Improved performance through caching and this code can be easily reused .

Please do review this PR @vivekvardhan2810 .
 Thank you!

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 please mention the issue number.

**Comment by T-Rahul-prabhu-38** [comment]
issue #80

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 why did you close this.

**Comment by T-Rahul-prabhu-38** [comment]
sir u told me to close this and send it with the dark mode feature right.

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 no Rahul, keep this open, I will look into it tomorrow.

**Comment by T-Rahul-prabhu-38** [comment]
ok sir.

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 resolve the conflicts.

**Comment by T-Rahul-prabhu-38** [comment]
sure sir

**Pull request closed without merging**
