### PR TITLE
Using_Trusted_Mail_Services_For_Signup

### PR DESCRIPTION
**Pull request by smog-root**
**Issue_id**: #586 

**Updated login.html:**

login.html

**Changes Made:**

**Email Domain Validation:**

Implemented a validation function that checks if the entered email belongs to an allowed domain (Gmail, Outlook, Yahoo).
If the email domain is invalid, an appropriate error message is displayed to the user.

**UI Enhancements:**

Error messages are now shown in real-time, providing immediate feedback to users on their input.

**Trusted mail services:**

gmail.com , outlook.com , yahoo.com , protonmail.com , icloud.com , tutanota.com , hotmail.com 

**_Note_**:- Add all labels added to issue #586 to this PR. So that GSSoC team can easily recognize the commit!

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@smog-root can you share the video proof of this, so that i can look and review it.

**Comment by smog-root** [comment]
@vivekvardhan2810 okay!

**Comment by smog-root** [comment]
You can access the preview of the commit using this link:- https://deploy-preview-587--ml-fusion-lab.netlify.app/

**Comment by vivekvardhan2810** [comment]
@smog-root i know i can access the preview and look in it and i know, but i want to look at it from your side. (like some video proof that you have done and it is running).

**Comment by smog-root** [comment]
Okay. Should I need to send screen recording?

**Comment by smog-root** [comment]
Okay wait a sec!

**Comment by smog-root** [comment]
**PROOF**:
[](https://mega.nz/file/oTFFgKSA#dQHMS_wGCUplJa8rXvwltTY_XsWlRqUe5LlcjikXLFQ)

**Comment by smog-root** [comment]
github is not allowing files more than 10MB. i don't know why you are asking me to send video proof! 

trust me i'm not a bot!

**Comment by vivekvardhan2810** [comment]
Done, @smog-root.

**Comment by smog-root** [comment]
add the labels dude!

**Pull request merged**
