### PR TITLE
Add Tutorial on Building and Evaluating a Neural Network from scratch to the project page

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Issues Identification

Closes: #1013 

## Description
This pull request introduces a comprehensive tutorial on building and evaluating a neural network from scratch using Python. The tutorial covers data preparation, model implementation, training, evaluation, and hyperparameter tuning. It serves as a foundational guide for beginners and intermediate learners interested in understanding the basics of neural networks and their practical applications.

### Details
- Tutorial Content:
  - Added a step-by-step guide to data preparation, including loading and preprocessing datasets.
  - Provided a detailed explanation of the neural network architecture implementation.
  - Included model training with customizable hyperparameters, such as learning rate and epochs.
  - Described the evaluation process, including accuracy calculation and predictions.
  - Offered insights into hyperparameter tuning and its impact on model performance.
  - Concluded with recommendations for further exploration and learning.

## Types of Changes

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] New and existing unit tests pass locally with my changes

## Screenshots

https://github.com/user-attachments/assets/59608b8a-bbde-49b1-abc0-cb02f3165a24

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]
LGTM

**Comment by vivekvardhan2810** [comment]
@IkkiOcean Thank you for contributing to ML Fusion Labs.

your contribution values to our project.

please do contribute to other projects also.

And wishing you all the best for your future endeavors.

**Comment by IkkiOcean** [comment]
@vivekvardhan2810 thanks a lot. this is my first time doing open source contribution and I really started to like it. I hope we collaborate in future sometime again.

**Comment by vivekvardhan2810** [comment]
@IkkiOcean we will collaborate for sure. you will like open source a lot and keep contributing. 😃

**Comment by vivekvardhan2810** [comment]
@IkkiOcean any suggestions on ML Fusion Labs and about me also.

**Comment by IkkiOcean** [comment]
@vivekvardhan2810 if you really like to move forward with this project, I recommend using react based frontend, its more stable and easy to develop. ML is still very unknown in India, so we can create a study hub for ML via ML fashion Lab.

**Comment by vivekvardhan2810** [comment]
@IkkiOcean we are also planning for this.

we have kept this for later.

**Comment by vivekvardhan2810** [comment]
@IkkiOcean and some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.

**Comment by IkkiOcean** [comment]
@vivekvardhan2810 I would say you were different among many. Many didnt took their role seriously and were offline half the time thoughout the event but I really liked that you were always their for contributors like us who are new to it. Keep going, I know being an admin of an open source community demands a lot of time and work but I really liked that you didnt quite it and gave your time to this event.

**Comment by vivekvardhan2810** [comment]
> @vivekvardhan2810 I would say you were different among many. Many didnt took their role seriously and were offline half the time thoughout the event but I really liked that you were always there for contributors like us who are new to it. Keep going, I know being an admin of an open source community demands a lot of time and work but I really liked that you didnt quite it and gave your time to this event.

Thank you @IkkiOcean for the compliments and I loved your work also mann.

Damn Good., you are a deemed contributor, Keep Going and all the best. Keep contributing to Open source.

**Pull request merged**
