### PR TITLE
Scroll button added

### LINKED ISSUE #5: Add scroll to top option
I would like to add this to the website please assign it to me and please add label to the issue

### PR DESCRIPTION
**Pull request by Khushi14404**
Added scroll button on all the pages

closes #5

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Khushi14404 pls resole the conflicts.

**Comment by Khushi14404** [comment]
@vivekvardhan2810 I'm a beginner and its my first time contributing so could you please tell me how can resolve this

**Comment by vivekvardhan2810** [comment]
@Khushi14404 just 

> @vivekvardhan2810 I'm a beginner and its my first time contributing so could you please tell me how can resolve this

it's just simple update the code of the files mentioned below, so that conflicts can be resolved and check the preview also.

image

**Comment by Khushi14404** [comment]
@vivekvardhan2810 can you check if it is correct or not

**Comment by vivekvardhan2810** [comment]
OKAY @Khushi14404 I will check it and merge it.

**Comment by vivekvardhan2810** [comment]
Good @Khushi14404.

Done.

**Pull request merged**
