### PR TITLE
Updated Footer of whole website

### PR DESCRIPTION
**Pull request by karthik-kiran-29**
image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@karthik-kiran-29 pls mention the issue number.

**Comment by karthik-kiran-29** [comment]
@vivekvardhan2810 https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues/175

**Comment by vivekvardhan2810** [comment]
@karthik-kiran-29 i think i have closed this issue

**Comment by karthik-kiran-29** [comment]
@vivekvardhan2810 I solved the issue which was part of it but footer problem still exists in the page.

**Comment by vivekvardhan2810** [comment]
Okay, done.

**Pull request merged**
