### PR TITLE
The community section #331

### PR DESCRIPTION
**Pull request by Lekkhasri**
## Issues Identification

Closes: #331 

## Description
The community section has been updated by adding them into the cards. Also add the dark and light mode toggle in it.
### Summary
The community section has been updated the font has been corrected, the arrow has been added, the toggle also added, the card are also aligned correctly , the invisible issue has also been rectified.
### Details
The home section has also been added in the header.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [  ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [  ] My code follows the style guidelines of this project
- [  ] I have performed a self-review of my own code
- [  ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [  ] My changes generate no new warnings
- [  ] My changes do not break the current system and pass all existing test cases
- [  ] I have added tests that prove my fix is effective or that my feature works
- [  ] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

## Additional Information

Please provide any other information that is relevant to this pull request.

Screenshot 2024-10-11 123007
Screenshot 2024-10-11 123037

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Lekkhasri pls resolve the conflicts.

**Comment by vivekvardhan2810** [comment]
@Lekkhasri while i was checking the preview.

i can't see the footer like the image mentioned below

image

And recently i have merged one file regarding community support page, i can't see the preview

and the font was changed, scroll top button is not there.

Make sure to sync the repository for the updated community support page and then you can update it.

**Comment by Lekkhasri** [comment]
@vivekvardhan2810  now verify it it has been resolved now.

**Comment by vivekvardhan2810** [comment]
@Lekkhasri good, but just make one change,

Recently, i have added the Resource library file in community support

image

I can't see it in preview.

Deploy Preview:

image

website:

image

and update the footer, as mentioned in below image.

image

**Comment by vivekvardhan2810** [comment]
Good @Lekkhasri Done.

**Comment by Lekkhasri** [comment]
@vivekvardhan2810  Thank you for your guidance

**Pull request merged**
