### PR TITLE
Added tutorial for creating pipeline for detecting phishing websites

### LINKED ISSUE #1104: [Mention The Feature]: Add complete tutorial page for creating pipeline for detecting phishing websites in projects page website
### Is your feature request related to a problem? Please describe.

Analyze protocols , meta-dataa , architecture , url , domain , ports , anchors , traffic and various other features of given url and detect whether the given website is malicious or not

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered.

_No response_

### Additional context.

_No response_

### Show us the magic with screenshots

https://github.com/user-attachments/assets/31c1aedc-3de8-4076-abc4-d65d37faf994

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
Fixes #1104 

## Issues Identification

Closes: #1104 

### Summary
A brief description of what this pull request does and why it is needed.

### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

https://github.com/user-attachments/assets/4e357198-d0ea-474d-bca8-e14428f18632

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by DarshAgrawal14** [comment]
Since this is not just a tutorial for model creation but rather a full pipeline, i would really appreciate it if you could update the level to level3?

**Comment by DarshAgrawal14** [comment]
thanks a lot , for being patient with me and listening to my request

**Comment by vivekvardhan2810** [comment]
sorry @DarshAgrawal14 i can give this for level 2 only, as these PR's are gonna review by program manager.

and gonna check the files.

so i can give you level 2 only.

i hope you understand.

**Review by vivekvardhan2810 — APPROVED** [review]

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 thank you for your contribution to ML Fusion Lab.

your contribution gives a value to us.

now please do work on other projects.

**Comment by DarshAgrawal14** [comment]
thanks man

**Pull request merged**
