### PR TITLE
Enhanced Scroll Button Design: Height, Width, Line-Height, and Color Adjustments

### PR DESCRIPTION
**Pull request by YOGINIMAHIMA1**
Height Adjustments: Increased the button's height for improved accessibility.
Width Adjustments: Modified the width to create a more balanced appearance.
Line-Height Adjustments: Optimized line-height for better text readability within the button.
Color Changes: Updated the color to enhance visibility and match the overall design theme.
image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@YOGINIMAHIMA1 pls mention the issue number.

**Comment by YOGINIMAHIMA1** [comment]
@vivekvardhan2810 #240 also merge this pr and mention the label as level1 and gssoc-ext

**Comment by vivekvardhan2810** [comment]
@YOGINIMAHIMA1 I asked issue number not Pull request number.

**Comment by vivekvardhan2810** [comment]
And @YOGINIMAHIMA1 I can see that you  didn't even created an issue and did Direct Pull Request. This is not a good Practice.

So I am closing the Pull Request.

**Comment by YOGINIMAHIMA1** [comment]
hey dont unmerged it i will show you the screen shot it is the issue which resolved so kindly create  pr merge @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@YOGINIMAHIMA1 you have created the issue now after doing the PR, So I have Closed it.

**Comment by YOGINIMAHIMA1** [comment]
@vivekvardhan2810 Ok but i have more issie so assign me that

**Comment by vivekvardhan2810** [comment]
Wait I will assign you, soon pls wait  @YOGINIMAHIMA1.

**Pull request closed without merging**
