### PR TITLE
Added Contributor's Page

### PR DESCRIPTION
**Pull request by TBorundia**
## Issues Identification

Closes: #495

## Description
I have added Contributor page that matches the overall theme of website.

## Types of Changes

- [ ] Bugfix (non-breaking change that fixes an issue)
-- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] My changes do not break the current system and pass all existing test cases
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Screenshots

https://github.com/user-attachments/assets/81b46b38-8306-435f-83b2-89d9c1767a1e

### CODE REVIEW

**Comment by TBorundia** [comment]
@vivekv2810 , Please review this PR.
Thank You !!

**Comment by vivekvardhan2810** [comment]
@TBorundia Can you Improve it like this.

image

**Comment by TBorundia** [comment]
@vivekvardhan2810 , Ok sir .
I will try to improve it.

**Comment by vivekvardhan2810** [comment]
@TBorundia can i close this PR, So that you can make Improvement.

**Comment by TBorundia** [comment]
image

@vivekvardhan2810 
Please review it now !!

**Comment by vivekvardhan2810** [comment]
@TBorundia it's looking good, just make some changes, 

Please Update the header and footer in contributors Page.

I can't see it.

image

**Comment by TBorundia** [comment]
@vivekvardhan2810 , Check it !!
image

**Comment by vivekvardhan2810** [comment]
@TBorundia Overall it's looking good.

just some small change, add the dark and light mode toggle button.

And change the font of the header as shown in home page.

**Comment by TBorundia** [comment]
@vivekvardhan2810 AS already website theme is black and grey , dark mode is not making a great change so I removed it.
Still you want that??

**Comment by vivekvardhan2810** [comment]
@TBorundia you can do one thing,

Choose other colour for the background

image

And if it suits then no problem, else then you can think for adding the toggle.

**Comment by vivekvardhan2810** [comment]
@TBorundia for now it is not a problem.

**Comment by TBorundia** [comment]
@vivekvardhan2810 So should I add that or only improve the header as home page??

**Comment by vivekvardhan2810** [comment]
@TBorundia for now just change the font for header, that's all.

image

**Comment by vivekvardhan2810** [comment]
Done, @TBorundia.

Good Job.

**Comment by TBorundia** [comment]
image

@vivekvardhan2810 , Check it now

**Pull request merged**
