### PR TITLE
Add blogs section

### PR DESCRIPTION
**Pull request by kanCHI-Singhal**
ADD BLOGS SECTION IN HOME PAGE AND NAVBAR.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal please mention your issue number.

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal while i was checking the preview, the about us button, community support button is looking like this

image

Please check and make the required changes.

**Comment by kanCHI-Singhal** [comment]
the issue number is #238.

**Comment by kanCHI-Singhal** [comment]
ok let me preview and resolve the conflicts by today.

**Comment by kanCHI-Singhal** [comment]
@vivekvardhan2810  sir , while previewing it i saw that while clicking on about us and community support page i got these pages 
Screenshot (507)
Screenshot (508)

yes, in blogs section left and right buttons are nor working , i will work on it and resolve the conflicts .

**Comment by vivekvardhan2810** [comment]
have you resolved the conflicts.

**Comment by kanCHI-Singhal** [comment]
No sir , actually i am new to github so i am not able to resolve the conflict, but please give me 1 more day , i will surely resolve the conflict. after 1 day if i cant then you can give it to any other person.
It will be highly appretiable if you give me 1 more day please.

**Comment by kanCHI-Singhal** [comment]
Ok, sir , Thank you so much sir for giving me more time.

**Comment by kanCHI-Singhal** [comment]
sir the conflict is arising again and again, can you please help me to resolve this conflict. it will be highly appretiable if you help me.

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal you can do one thing, i will be closing this PR, make sure to sync the repository and then update it, will it be okay for you, if i close this PR.

**Comment by kanCHI-Singhal** [comment]
yes sir , you can do this, may be this helps me, It will be highly appretiable .

**Comment by vivekvardhan2810** [comment]
Closing this PR.

**Comment by kanCHI-Singhal** [comment]
Sir now should I have to create a new PR?

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal make sure to sync the repository and then update it and then Create New PR.

**Comment by kanCHI-Singhal** [comment]
ok sir

**Pull request closed without merging**
