### PR TITLE
changes to nav bar and logo on every tabs is done for issue #45

### PR DESCRIPTION
**Pull request by Iampratyush004**
@vivekvardhan2810  sir kindly see to this request 
key changes:
now the user can experience logo and navigation menu design on every tab 

please tag hacktoberfest and gssoc-extd

### CODE REVIEW

**Comment by Iampratyush004** [comment]
@vivekvardhan2810  Sir no matter if you have registered the project in hacktoberfest.. if you label them with hacktoberfest..it will be counted within 7 days after review from maintainers.

and kindly see to my pull request over this issue

**Comment by Iampratyush004** [comment]
@vivekvardhan2810 sir i think gamerking isn't going to respond with any changes.. u may plz to proceed with what we had talked about.
thanks

**Comment by vivekvardhan2810** [comment]
@Iampratyush004 let's wait for the 2 days, we have to give the time.

**Comment by Iampratyush004** [comment]
> @Iampratyush004 let's wait for the 2 days, we have to give the time.

ok sir

**Comment by vivekvardhan2810** [comment]
@Iampratyush004 pls resolve the conflicts.

**Comment by Iampratyush004** [comment]
@vivekvardhan2810  sir conflicts resolved

**Pull request closed without merging**
