### PR TITLE
Responsiveness of home  page 

### PR DESCRIPTION
**Pull request by Palmistry2310**
## Issues Identification

Closes: #803 

## Description
made homepage responsive.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe):responsiveness

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

https://github.com/user-attachments/assets/684ec1e3-fdbb-4e26-9a49-373f080ef11c

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 i can't see any file changes from your side.

image

**Comment by Palmistry2310** [comment]
@vivekvardhan2810 actually by mistake i commited in main branch so i reverted it. created new branch and then commited again. thats why is it showing like this ?

but on opening this it's showing the changes
image

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 you can do one thing, you can close this PR,

and sync the repository, then commit and then create new Pull Request,

will it be okay for you.

**Comment by Palmistry2310** [comment]
i am so sorry , after creating pr i saw it. should i close this pr and make all changes in the new branch created and do it again?

**Comment by vivekvardhan2810** [comment]
> i am so sorry , after creating pr i saw it. should i close this pr and make all changes in the new branch created and do it again?

@Palmistry2310 yes you can do this.

**Comment by Palmistry2310** [comment]
> @Palmistry2310 you can do one thing, you can close this PR,
> 
> and sync the repository, then commit and then create new Pull Request,
> 
> will it be okay for you.

okay

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 i have closed this PR.

and sync the repository, then commit and then create new Pull Request,

**Pull request closed without merging**
