### PR TITLE
Fixed `Terms & Conditions Page` + Add 10 `Project Detail Pages` to Cards Under Project Section of website

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
Minor Update to `Terms & Conditions Page` + Add 10 `Project Detail Pages` to Cards Under Project Section of website

Closes: #1046 

# Description
-  made links clickable at `terms and condition` page

https://github.com/user-attachments/assets/ffa0204c-08ba-49e5-9060-37f51c2824d2

-  Following `Project Detail Pages` are added:
1. Traffic Accident Prediction System  
2. Personalized Learning Recommendation System  
3. AI for Mental Health Analysis  
4. AI-Driven Disaster Relief Supply Chain Optimization  
5. Urban Sound Classification  
6. Smart Home Energy Prediction  
7. AI for Personalized Nutrition Plans  
8. Plastic Waste Classification To Recycle  
9. AI-Powered Virtual Therapist  
10. Human Face Landmark Detection

## Added all ten pages like this
https://github.com/user-attachments/assets/f6512202-9ba9-4a1f-84ce-fc858ba18568

@vivekvardhan2810 

## Types of Changes

- [x] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 thank you for contributing to ML Fusion Labs.

your contribution gives a value to us.

Now please do work on other projects.

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 can you please share some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.

And how much i was actively working on this.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 can you please share some feedback about me also, like how was my role and collaboration with you as a project admin and contributor.
> 
> And how much i was actively working on this.


It’s been a great experience working with you as the project admin for the ML Fusion website....You’ve always been active and quick to respond, getting issues assigned and PRs reviewed right away. I think it helped not just me but all the contributors involved... That's why many prefers to contribute more to this project because we never had to wait for long time...
Your clear communication was very helpful in case of assigning isse or reviewing prs.


 Lots of learning for me !! Thanks so much!
@vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Thank you @Adarsh-Chaubey03 for the compliments and I loved your work also mann.

Damn Good., you are a deemed contributor, Keep Going and all the best. Keep contributing to Open source.

**Pull request merged**
