### PR TITLE
feat: Use display none to hide cursor follower outside page boundaries #1074

### PR DESCRIPTION
**Pull request by CoderFleet**
### Changes Made
- **Added**: `display: none` for `.circle` elements when the cursor exits the page.
- **Added**: `display: block` for `.circle` elements when the cursor re-enters the page.
- **Improved**: Prevents cursor follower from "sticking" at page edges, particularly when the cursor exits the visible area, offering a smoother visual experience and reducing rendering load.

## Issues Identification

Closes: #1074 

### Summary
This PR introduces an enhancement to the cursor follower feature, ensuring it only appears while the cursor is within the page boundaries. By toggling display: none and display: block based on cursor position, this update improves performance and provides a smoother, cleaner user experience.

### Details
- **Display Toggle**: Replaces opacity toggling with `display: none` and `display: block` for the `.circle` elements, improving visual transitions and performance.
- **Boundary Control**: Ensures `.circle` elements are only visible within the page area, hiding them immediately when the cursor exits.
- **Smoother Transitions**: Prevents cursor follower from "sticking" at page edges, especially on rapid cursor exits, creating a cleaner and more responsive effect.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots

image
image

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@CoderFleet thank you for contribution to ML Fusion Lab.

your contribution gives a value to us.

now please do work on other projects.

**Comment by vivekvardhan2810** [comment]
@CoderFleet sorry that if i have troubled you.

**Comment by CoderFleet** [comment]
No! Not at all. Even though I worked on minimal issue, it was an enjoyable experience
In the future, if you decide to become active in this project, I would love to help.

**Comment by vivekvardhan2810** [comment]
@CoderFleet thank you.

now please do work on other projects.

And wishing you all the best from my side for your future endeavors.

**Pull request merged**
