### PR TITLE
only can take 10 digits for phone number

### LINKED ISSUE #875: in the contact us form mobile number is taking more than 10 digits
### Description

in the contact us form mobile number is taking more than 10 digits

### Steps to Reproduce

we can modify it to take only 10 digits

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Screenshots

Screenshot 2024-10-20 124413

### Additional Information

_No response_

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by Ritikabiswas**
Not so big change 
It was my first time 

fixes #875

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Ritikabiswas please mention the issue number.

**Comment by Ritikabiswas** [comment]
issue number 875

**Comment by vivekvardhan2810** [comment]
@Ritikabiswas Merged, Thank you.

And please do contribute to other projects.

**Comment by Ritikabiswas** [comment]
Thank u so much

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @vivekvardhan2810

**Pull request merged**
