### PR TITLE
[FIX] "Scroll to Top" Button and CSS of projects

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Issues Identification

- Closes: #675 

## Description

This pull request addresses two primary updates:
1. **Removal of Redundant CSS**: 
   - Cleaned up and removed unused or repetitive CSS rules on the projects page.
   - Consolidated styling for project elements to reduce redundancy and improve maintainability.

2. **Scroll-to-Top Button Correction**:
   - Fixed a scroll-to-top button that becomes visible when the user scrolls down the projects page.
 
### Details
- Refactored the CSS for the project cards and other related components by combining similar styles and eliminating duplication.
- Improved performance by reducing the overall size of the CSS file.
- The scroll-to-top button is accessible and styled.

## Screenshots

https://github.com/user-attachments/assets/5105cb62-df4d-4fab-b172-dda1d41fdcf5

https://github.com/user-attachments/assets/9f2561b3-9d17-44bb-abf1-a52dae70c690

### CODE REVIEW

**Comment by IkkiOcean** [comment]
please provide level 3 as multiple files were involved and clearing the multiple redundant css was very important for performance of the application

**Comment by Hemu21** [comment]
@MastanSayyad

**Comment by vivekvardhan2810** [comment]
@MastanSayyad

Please tell me which level can i change to this.

**Comment by vivekvardhan2810** [comment]
@MastanSayyad i have changed the level.

please check it.

**Pull request merged**
